import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMissionControl } from '../../context/MissionControlContext';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { Badge } from '../ui/Badge';
export const EvidenceCenterSection = () => {
    const { state } = useMissionControl();
    const { evidenceItems } = state;
    return (_jsx("section", { className: "w-full mt-8", children: _jsxs(Card, { variant: "default", className: "border-[#1E293B] bg-[#0F172A]/80 backdrop-blur-md", children: [_jsxs(CardHeader, { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: "STAGE 7 \u2022 LINEAGE LEDGER" }), _jsxs("span", { className: "text-xs text-[#94A3B8] font-mono", children: [evidenceItems.length, " Verified Evidence Sources"] })] }), _jsx(CardTitle, { className: "mt-2 text-lg lg:text-xl font-bold text-[#F8FAFC]", children: "Empirical Evidence & SLSA Lineage Ledger" }), _jsx("p", { className: "mt-1 text-xs text-[#94A3B8]", children: "Never fabricate evidence. Every reported metric is cryptographically traceable from raw scan observation to final statistical claim." })] }), _jsx("div", { className: "flex items-center gap-2 bg-[#131D35] px-3.5 py-2 rounded-xl border border-[#334155]/60 text-xs font-mono text-[#10B981]", children: _jsx("span", { children: "SLSA Level 3+ Compliant" }) })] }), _jsx(CardContent, { className: "p-6 space-y-4", children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: evidenceItems.map((item) => (_jsxs("div", { className: "p-4 rounded-xl bg-[#131D35] border border-[#1E293B] hover:border-cyan-500/40 transition-all flex flex-col justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-[10px] font-mono bg-[#0A0F1D] text-cyan-300 px-2 py-0.5 rounded border border-cyan-500/30", children: item.sourceType }), _jsx(Badge, { variant: "success", size: "sm", children: item.slsaLevel })] }), _jsx("h4", { className: "mt-2 text-sm font-semibold text-[#F8FAFC]", children: item.title }), _jsxs("p", { className: "mt-1 text-xs font-mono text-[#94A3B8] truncate", title: item.origin, children: ["Source: ", item.origin] })] }), _jsxs("div", { className: "mt-4 pt-3 border-t border-[#1E293B] space-y-1.5 text-xs font-mono", children: [_jsxs("div", { className: "flex items-center justify-between text-[#64748B]", children: [_jsx("span", { children: "Sample Size:" }), _jsxs("span", { className: "text-[#F8FAFC] font-bold", children: ["n=", item.sampleCount] })] }), _jsxs("div", { className: "flex items-center justify-between text-[#64748B]", children: [_jsx("span", { children: "Confidence Added:" }), _jsxs("span", { className: "text-[#10B981] font-bold", children: ["+", (item.confidenceContribution * 100).toFixed(1), "%"] })] }), _jsxs("div", { className: "flex items-center justify-between text-[#64748B] pt-1", children: [_jsx("span", { children: "Digest:" }), _jsxs("span", { className: "text-[#A855F7] truncate max-w-[140px]", title: item.sha256Digest, children: [item.sha256Digest.substring(0, 10), "..."] })] })] })] }, item.id))) }) })] }) }));
};
