import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMissionControl } from '../../context/MissionControlContext';
import { Badge } from '../ui/Badge';
import { StatusIndicator } from '../ui/StatusIndicator';
import { Button } from '../ui/Button';
export const HeroHeader = () => {
    const { state, toggleLiveSimulation } = useMissionControl();
    const { mission, confidenceData, isPaused } = state;
    const formatElapsed = (seconds) => {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins}m ${secs < 10 ? '0' : ''}${secs}s`;
    };
    return (_jsxs("header", { className: "relative w-full rounded-2xl bg-[#0F172A]/90 border border-[#1E293B] shadow-2xl p-6 lg:p-8 backdrop-blur-xl overflow-hidden", children: [_jsx("div", { className: "absolute -top-24 -right-24 w-96 h-96 bg-gradient-to-br from-blue-600/15 to-cyan-400/10 rounded-full blur-3xl pointer-events-none" }), _jsxs("div", { className: "flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Badge, { variant: "intelligence", size: "md", hasDot: true, isPulsing: true, children: "AUTONOMOUS RUNTIME" }), _jsx("span", { className: "text-xs font-mono text-[#94A3B8]", children: "v2.5-enterprise \u2022 SLSA L3+" })] }), _jsx("h1", { className: "mt-3 text-2xl lg:text-4xl font-extrabold text-[#F8FAFC] tracking-tight", children: "DocuTask Agent" }), _jsx("p", { className: "mt-1 text-base lg:text-lg font-medium text-[#38BDF8]", children: "An Autonomous AI Coworker for Enterprise Document Operations" }), _jsx("p", { className: "mt-2 text-xs lg:text-sm text-[#94A3B8] max-w-3xl leading-relaxed", children: "AI that understands document-processing goals, plans workflows, executes tools, validates results, learns from experience, and improves until statistical confidence targets are met." })] }), _jsxs("div", { className: "flex flex-col items-start lg:items-end gap-3 shrink-0", children: [_jsx("div", { className: "flex items-center gap-2 bg-[#131D35] px-3.5 py-2 rounded-xl border border-[#334155]/60 shadow-inner", children: _jsx(StatusIndicator, { status: isPaused ? 'waiting' : 'executing', label: isPaused ? 'Mission Paused' : 'Autonomous Cognition Active', sublabel: `Heartbeat: ${new Date().toISOString().substring(11, 19)} UTC`, showPulse: !isPaused }) }), _jsx("div", { className: "flex items-center gap-2", children: _jsx(Button, { variant: "ghost", size: "sm", onClick: toggleLiveSimulation, className: "text-xs font-mono", children: state.isSimulatingLive ? '● Live Stream ON' : '○ Live Stream PAUSED' }) })] })] }), _jsxs("div", { className: "mt-8 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 pt-6 border-t border-[#1E293B]/80 relative z-10", children: [_jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-[#1E293B]", children: [_jsx("span", { className: "text-[11px] font-medium text-[#64748B] block", children: "Current Mission" }), _jsx("span", { className: "text-xs font-bold font-mono text-[#F8FAFC] block truncate mt-0.5", children: mission.missionId }), _jsx("span", { className: "text-[10px] text-[#38BDF8] font-mono block mt-0.5", children: mission.missionType })] }), _jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-[#1E293B]", children: [_jsx("span", { className: "text-[11px] font-medium text-[#64748B] block", children: "Mission State" }), _jsx("div", { className: "mt-1", children: _jsx(Badge, { variant: mission.currentState === 'ACTIVE'
                                        ? 'success'
                                        : mission.currentState === 'PAUSED'
                                            ? 'warning'
                                            : 'default', size: "sm", hasDot: true, children: mission.currentState }) })] }), _jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-[#1E293B]", children: [_jsx("span", { className: "text-[11px] font-medium text-[#64748B] block", children: "Elapsed Time" }), _jsx("span", { className: "text-sm font-semibold font-mono text-[#F8FAFC] block mt-0.5", children: formatElapsed(mission.elapsedSeconds) }), _jsxs("span", { className: "text-[10px] text-[#64748B] block", children: ["Started: ", mission.startedAtUtc.substring(11, 19)] })] }), _jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-cyan-500/20", children: [_jsx("span", { className: "text-[11px] font-medium text-cyan-400 block", children: "Statistical Confidence" }), _jsxs("span", { className: "text-sm font-bold font-mono text-[#00D2FF] block mt-0.5", children: [(confidenceData.currentConfidence * 100).toFixed(1), "%"] }), _jsxs("span", { className: "text-[10px] text-[#64748B] font-mono block", children: ["Target: ", (confidenceData.targetConfidence * 100).toFixed(0), "% (n=", confidenceData.sampleSize, ")"] })] }), _jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-[#1E293B]", children: [_jsx("span", { className: "text-[11px] font-medium text-[#64748B] block", children: "Budget Burn" }), _jsxs("span", { className: "text-xs font-semibold font-mono text-[#F8FAFC] block mt-0.5", children: ["$", mission.budgetConsumedUsd.toFixed(2), " / $", mission.budgetAllocatedUsd.toFixed(2)] }), _jsxs("span", { className: "text-[10px] text-[#64748B] font-mono block", children: [mission.hardwareHoursUsed.toFixed(2), " hrs hardware"] })] }), _jsxs("div", { className: "bg-[#131D35]/60 p-3 rounded-lg border border-[#1E293B]", children: [_jsx("span", { className: "text-[11px] font-medium text-[#64748B] block", children: "Canonical Digest" }), _jsxs("span", { className: "text-[11px] font-mono text-[#A855F7] block truncate mt-0.5 cursor-pointer hover:underline", title: mission.canonicalDigestSha256, children: [mission.canonicalDigestSha256.substring(0, 12), "..."] }), _jsx("span", { className: "text-[10px] text-[#10B981] font-mono block", children: "\u2713 SHA-256 Verified" })] })] })] }));
};
