import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useMissionControl } from '../../context/MissionControlContext';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
export const HumanControlSection = () => {
    const { state, pauseMission, resumeMission, abortMission, injectSentinelState, resetInitialState, } = useMissionControl();
    const { isPaused, humanAuditLogs } = state;
    const [abortReason, setAbortReason] = useState('');
    const [showAbortPrompt, setShowAbortPrompt] = useState(false);
    return (_jsx("section", { className: "w-full mt-8 mb-12", children: _jsxs(Card, { variant: "default", className: "border-[#1E293B] bg-[#0F172A]/80 backdrop-blur-md", children: [_jsx(CardHeader, { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: "STAGE 10 \u2022 HUMAN + AI COLLABORATION" }), _jsxs("span", { className: "text-xs text-[#94A3B8] font-mono", children: [humanAuditLogs.length, " Cryptographic Audit Receipts"] })] }), _jsx(CardTitle, { className: "mt-2 text-lg lg:text-xl font-bold text-[#F8FAFC]", children: "Human Control & Governance Cockpit" }), _jsx("p", { className: "mt-1 text-xs text-[#94A3B8]", children: "The operator retains full supervisory authority. Interrupt, pause, inspect, override, or inject Zero-Fabrication sentinels with deterministic audit logging." })] }) }), _jsxs(CardContent, { className: "p-6 space-y-6", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3 p-4 rounded-xl bg-[#131D35] border border-[#1E293B]", children: [isPaused ? (_jsx(Button, { variant: "intelligence", size: "md", onClick: () => resumeMission('Operator manual resume'), children: "\u25B6 Resume Autonomous Cognition" })) : (_jsx(Button, { variant: "secondary", size: "md", onClick: () => pauseMission('Operator manual pause'), children: "\u23F8 Pause Mission" })), _jsx(Button, { variant: "outline", size: "md", onClick: injectSentinelState, className: "text-amber-400 border-amber-500/40 hover:bg-amber-950/30", children: "\u26A0 Simulate Zero-Fabrication Sentinel" }), _jsx(Button, { variant: "ghost", size: "md", onClick: resetInitialState, children: "\uD83D\uDD04 Reset Initial Demo State" }), _jsx(Button, { variant: "danger", size: "md", onClick: () => setShowAbortPrompt(true), children: "\u23F9 Abort Mission" })] }), showAbortPrompt && (_jsxs("div", { className: "p-4 rounded-xl bg-red-950/40 border border-red-500/40 space-y-3", children: [_jsx("h4", { className: "text-xs font-bold text-red-400 uppercase tracking-wider", children: "Confirm Mission Abort Action" }), _jsx("p", { className: "text-xs text-[#94A3B8]", children: "Please enter a formal reason for terminating this autonomous mission. An append-only audit receipt will be signed." }), _jsx("input", { type: "text", value: abortReason, onChange: (e) => setAbortReason(e.target.value), placeholder: "Reason for aborting mission...", className: "w-full bg-[#131D35] border border-[#334155] rounded-lg px-3 py-2 text-xs font-mono text-[#F8FAFC] focus:outline-none focus:border-red-400" }), _jsxs("div", { className: "flex justify-end gap-2", children: [_jsx(Button, { variant: "ghost", size: "sm", onClick: () => setShowAbortPrompt(false), children: "Cancel" }), _jsx(Button, { variant: "danger", size: "sm", onClick: () => {
                                                abortMission(abortReason || 'Operator termination');
                                                setShowAbortPrompt(false);
                                            }, children: "Confirm Abort" })] })] })), _jsxs("div", { children: [_jsx("span", { className: "text-[11px] font-bold uppercase tracking-wider text-[#64748B] block mb-3", children: "Supervisory Audit Receipts (Signed & Immutable)" }), _jsx("div", { className: "space-y-2", children: humanAuditLogs.map((log) => (_jsxs("div", { className: "p-3 rounded-lg bg-[#131D35]/70 border border-[#1E293B] flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs font-mono", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-[#00D2FF] font-bold", children: ["[", log.timestampUtc, "]"] }), _jsx(Badge, { variant: "intelligence", size: "sm", children: log.action }), _jsx("span", { className: "text-[#F8FAFC]", children: log.reason })] }), _jsxs("div", { className: "flex items-center gap-3 text-[#64748B] text-[11px] shrink-0", children: [_jsxs("span", { children: ["By: ", log.triggeredBy] }), _jsxs("span", { className: "text-[#A855F7] truncate max-w-[120px]", title: log.auditSha256Receipt, children: ["Receipt: ", log.auditSha256Receipt.substring(0, 8), "..."] })] })] }, log.id))) })] })] })] }) }));
};
