import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useWorkspace } from '../context/WorkspaceContext';
import { CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { CommandInput } from './CommandInput';
export const ConversationPanel = () => {
    const { chatMessages, sendUserCommand, isDemoRunning } = useWorkspace();
    return (_jsxs("div", { className: "w-full flex flex-col h-[700px] rounded-2xl bg-[#0F172A]/90 border border-[#1E293B] shadow-2xl overflow-hidden", children: [_jsxs(CardHeader, { className: "flex flex-row items-center justify-between py-4 px-6 border-b border-[#1E293B] bg-[#131D35]/50", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "sm", hasDot: true, isPulsing: true, children: "AI COWORKER ACTIVE" }), _jsx("span", { className: "text-xs text-[#94A3B8] font-mono", children: "Natural Language Intent Engine" })] }), _jsx(CardTitle, { className: "mt-1 text-base font-bold text-[#F8FAFC]", children: "Interactive Collaboration Stream" })] }), _jsx("div", { className: "flex items-center gap-2 text-xs font-mono text-[#38BDF8] bg-[#0A0F1D] px-3 py-1.5 rounded-lg border border-cyan-500/30", children: _jsx("span", { children: "Zero-Fabrication Guard: ON" }) })] }), _jsx(CardContent, { className: "flex-1 overflow-y-auto p-6 space-y-4", children: chatMessages.map((msg) => {
                    const isUser = msg.sender === 'HUMAN';
                    return (_jsxs("div", { className: `flex flex-col ${isUser ? 'items-end' : 'items-start'}`, children: [_jsx("div", { className: "flex items-center gap-2 mb-1 text-[11px] font-mono", children: isUser ? (_jsxs("span", { className: "text-[#94A3B8]", children: ["You (Operator) \u2022 ", msg.timestampUtc] })) : (_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "font-bold text-[#00D2FF]", children: "DocuTask Agent" }), msg.agentRole && (_jsx(Badge, { variant: "intelligence", size: "sm", children: msg.agentRole })), _jsxs("span", { className: "text-[#64748B]", children: ["\u2022 ", msg.timestampUtc] })] })) }), _jsxs("div", { className: `max-w-2xl p-4 rounded-2xl text-xs sm:text-sm leading-relaxed ${isUser
                                    ? 'bg-[#0066FF] text-white rounded-tr-none shadow-[0_0_15px_rgba(0,102,255,0.3)]'
                                    : 'bg-[#131D35] border border-[#334155] text-[#F8FAFC] rounded-tl-none shadow-lg'}`, children: [_jsx("p", { className: "whitespace-pre-wrap", children: msg.text }), msg.proposedPlanUpdate && msg.proposedPlanUpdate.length > 0 && (_jsxs("div", { className: "mt-3 p-3 rounded-xl bg-[#0A0F1D]/80 border border-cyan-500/30 space-y-1.5 font-mono text-xs", children: [_jsx("span", { className: "text-[10px] font-bold text-[#00D2FF] uppercase tracking-wider block", children: "Proposed DAG Adaptation:" }), msg.proposedPlanUpdate.map((step, i) => (_jsxs("div", { className: "flex items-start gap-2 text-[#94A3B8]", children: [_jsx("span", { className: "text-[#10B981]", children: "\u2794" }), _jsx("span", { children: step })] }, i)))] })), msg.actionTaken && (_jsxs("div", { className: "mt-2 pt-2 border-t border-[#1E293B] flex items-center justify-between text-[11px] font-mono", children: [_jsxs("span", { className: "text-[#10B981]", children: ["\u26A1 ", msg.actionTaken] }), msg.confidenceScore && (_jsxs("span", { className: "text-[#00D2FF]", children: ["Confidence: ", (msg.confidenceScore * 100).toFixed(1), "%"] }))] }))] }), msg.suggestedQuickActions && msg.suggestedQuickActions.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-2 mt-2", children: msg.suggestedQuickActions.map((qa) => (_jsxs(Button, { variant: "ghost", size: "sm", onClick: () => sendUserCommand(qa), className: "text-[11px] bg-[#131D35] border border-[#1E293B] hover:border-cyan-400 hover:text-[#00D2FF]", children: ["\uD83D\uDCAC ", qa] }, qa))) }))] }, msg.id));
                }) }), _jsx("div", { className: "p-4 border-t border-[#1E293B] bg-[#131D35]/70", children: _jsx(CommandInput, { onSendCommand: sendUserCommand, disabled: isDemoRunning }) })] }));
};
