"""Audit Export Formats (JSON, CSV, Markdown Compliance Dossier)."""

import csv
import io
import json
from typing import List, Dict, Any
from ..core.events import AuditEvent
from ..evidence.manager import EvidenceBundle


class AuditExporter:
    """Formats and exports audit events and evidence packages into various portable representations."""

    @staticmethod
    def to_json(events: List[AuditEvent], indent: int = 2) -> str:
        """Serializes audit events to formatted JSON."""
        data = [e.model_dump(mode="json") for e in events]
        return json.dumps(data, indent=indent, default=str)

    @staticmethod
    def to_csv(events: List[AuditEvent]) -> str:
        """Exports audit events to standard CSV."""
        if not events:
            return ""

        output = io.StringIO()
        fieldnames = [
            "event_id",
            "timestamp",
            "tenant_id",
            "category",
            "event_type",
            "actor_id",
            "actor_type",
            "action",
            "resource_type",
            "resource_id",
            "severity",
            "outcome",
            "risk_score",
            "correlation_id",
            "integrity_hash",
        ]
        writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()

        for ev in events:
            row = ev.model_dump(mode="json")
            writer.writerow(row)

        return output.getvalue()

    @staticmethod
    def to_markdown_dossier(bundle: EvidenceBundle) -> str:
        """Generates an executive compliance and audit verification markdown dossier."""
        lines = [
            f"# Audit & Compliance Evidence Dossier: {bundle.title}",
            f"**Tenant ID:** `{bundle.tenant_id}`  ",
            f"**Bundle ID:** `{bundle.bundle_id}`  ",
            f"**Generated By:** {bundle.generated_by}  ",
            f"**Generated At:** {bundle.generated_at.isoformat()}  ",
            f"**Manifest Hash:** `{bundle.manifest_hash}`  ",
            f"**Cryptographic Signature:** `{bundle.signature[:32]}...`  ",
            "",
            "## 1. Executive Summary",
            f"**Purpose:** {bundle.purpose}  ",
            f"**Total Audit Events Captured:** {len(bundle.audit_events)}  ",
            f"**Total Evidence Artifacts Attached:** {len(bundle.artifacts)}  ",
            "",
            "## 2. Chronological Audit Trail",
            "| Timestamp | Event ID | Actor | Action | Resource | Outcome | Severity |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ]

        for ev in bundle.audit_events[:50]:  # Cap first 50 in preview
            actor_str = f"{ev.actor_id} ({ev.actor_type.value if hasattr(ev.actor_type, 'value') else ev.actor_type})"
            outcome_str = ev.outcome.value if hasattr(ev.outcome, 'value') else str(ev.outcome)
            sev_str = ev.severity.value if hasattr(ev.severity, 'value') else str(ev.severity)
            lines.append(
                f"| {ev.timestamp.strftime('%Y-%m-%d %H:%M:%S')} | `{ev.event_id}` | {actor_str} | {ev.action} | {ev.resource_type}:{ev.resource_id} | {outcome_str} | {sev_str} |"
            )

        lines.extend([
            "",
            "## 3. Evidence Artifacts",
            "| Evidence ID | Name | Type | Source | SHA-256 Hash |",
            "| :--- | :--- | :--- | :--- | :--- |",
        ])

        for art in bundle.artifacts:
            type_str = art.evidence_type.value if hasattr(art.evidence_type, 'value') else str(art.evidence_type)
            lines.append(
                f"| `{art.evidence_id}` | {art.name} | {type_str} | {art.source} | `{art.content_hash[:24]}...` |"
            )

        lines.append("")
        lines.append("---")
        lines.append("*Generated by DocuTask Enterprise Audit Platform (Phase 8G)*")
        return "\n".join(lines)
