/**
 * Realistic Mock Initial State for DocuTask Agent Mission Control
 *
 * Demonstrates an autonomous AI coworker optimizing complex invoice extraction
 * and reconciliation under Zero-Fabrication principles and full explainability.
 */
export const initialMissionControlState = {
    mission: {
        missionId: 'mission_autocog_799784',
        title: 'Autonomous Multi-Tier OCR & Entity Reconciliation Mission',
        goalStatement: 'Analyze noisy degraded invoice scans, adapt binarization parameters, extract line items, and prove >=95% statistical confidence without human intervention.',
        currentState: 'ACTIVE',
        owner: 'DocuTask Autonomous Runtime (Worker-10)',
        startedAtUtc: '2026-09-09T09:15:00Z',
        elapsedSeconds: 1240,
        priority: 'HIGH',
        missionType: 'BENCHMARK_OPTIMIZATION',
        confidenceScore: 0.972,
        budgetAllocatedUsd: 15.00,
        budgetConsumedUsd: 2.14,
        hardwareHoursUsed: 1.25,
        readinessScore: 0.96,
        canonicalDigestSha256: '5fc03ae31fe41fce3f73ffab2fec820f46c3ef6be0b9efc7d7e63459c04297a7',
    },
    goalIntelligence: {
        goalId: 'goal_invoice_noisy_q3',
        rawGoalStatement: 'Extract line items and tax totals from noisy enterprise utility invoices with >95% confidence and verified lineage.',
        currentPhase: 'COMPILATION',
        phaseStatus: {
            understanding: 'COMPLETED',
            reasoning: 'COMPLETED',
            negotiation: 'COMPLETED',
            utilityAnalysis: 'COMPLETED',
            compilation: 'COMPLETED',
        },
        understanding: {
            intent: 'Automate noisy invoice OCR parameter tuning and field extraction with statistical error boundaries.',
            extractedEntities: {
                'Document Domain': 'Utility Invoices & Receipts',
                'Target Fields': 'InvoiceNumber, TotalAmount, TaxRate, VendorName, LineItems',
                'Target Metric': 'Weighted Field F1 Score (Macro)',
            },
            constraints: [
                'Hardware budget <= $15.00 USD',
                'Zero fabrication: Emit UNKNOWN when confidence bounds are violated',
                'Enforce SLSA Level 3+ provenance on all produced JSON line items',
            ],
            allocatedResources: {
                maxHours: 4.0,
                maxBudgetUsd: 15.00,
            },
            deadlineUtc: '2026-09-09T18:00:00Z',
            requiredCapabilities: ['OCR_PREPROCESS', 'ADAPTIVE_THRESHOLD', 'LAYOUT_PARSER', 'STATISTICAL_POWER_CALC', 'MERKLE_AUDIT'],
            riskSummary: 'Low hallucination risk due to strict OCR ground truth matching and double-pass cross validation.',
            missingInformation: [],
        },
        reasoning: {
            derivedRequirements: [
                'Run adaptive contrast optimization before OCR pass',
                'Sample >= 50 ground truth patches for statistical power >= 0.80',
                'Verify zero regression against baseline SROIE benchmarks',
            ],
            requiredDatasets: ['SROIE_INVOICES_V2', 'SYNTHETIC_NOISY_RECEIPTS_V1'],
            requiredBenchmarks: ['Character Error Rate (CER)', 'Field Extraction F1', 'Latency p95'],
            evaluationMetrics: ['Precision', 'Recall', 'F1-Score', 'SLSA Provenance Hash'],
            groundTruthAvailability: '100% verified via sha256 checksums on reference annotations',
            expectedDeliverables: ['Structured JSON Lineage', 'LaTeX Research Table', 'Confidence Audit Certificate'],
            publicationStandards: ['ACM Artifact Review Ready', 'NIST AI RMF Compliant'],
        },
        negotiation: {
            participants: [
                {
                    agentRole: 'PLANNER',
                    stance: 'APPROVE',
                    rationale: 'Compiled 6-node DAG with fallback binarization routes.',
                    confidence: 0.98,
                    timestampUtc: '2026-09-09T09:15:05Z',
                },
                {
                    agentRole: 'MEMORY',
                    stance: 'APPROVE',
                    rationale: 'Recalled 18 previous similar thermal scan missions; recommended contrast boost 1.25.',
                    confidence: 0.94,
                    timestampUtc: '2026-09-09T09:15:06Z',
                },
                {
                    agentRole: 'GOVERNANCE',
                    stance: 'APPROVE',
                    rationale: 'All privacy masks verified; no unredacted PII in debug streams.',
                    confidence: 0.99,
                    timestampUtc: '2026-09-09T09:15:08Z',
                },
                {
                    agentRole: 'COORDINATOR',
                    stance: 'APPROVE',
                    rationale: 'Full inter-agent consensus achieved (Score: 0.97).',
                    confidence: 0.97,
                    timestampUtc: '2026-09-09T09:15:09Z',
                },
            ],
            consensusScore: 0.97,
            remainingDisagreements: [],
            isConsensusAchieved: true,
        },
        utility: {
            expectedBenefit: 0.92,
            probabilityOfSuccess: 0.95,
            strategicValue: 0.88,
            noveltyScore: 0.74,
            researchImpact: 0.85,
            estimatedCostUsd: 2.14,
            riskScore: 0.12,
            overallUtilityScore: 0.89,
        },
        missionCompilation: {
            generatedDagNodesCount: 6,
            milestonesCount: 3,
            tasksCount: 6,
            estimatedRuntimeMinutes: 25,
            stoppingThresholdConfidence: 0.95,
        },
    },
    cognitionLoop: [
        {
            stage: 'GOAL',
            label: 'Goal Definition',
            status: 'COMPLETED',
            startedAtUtc: '09:15:00',
            completedAtUtc: '09:15:03',
            durationMs: 3000,
            confidenceScore: 0.99,
            summary: 'Goal parsed, validated, and normalized into measurable domain model.',
            artifactsProduced: ['goal_spec.json'],
            evidenceCount: 1,
        },
        {
            stage: 'OBSERVE',
            label: 'Observation & Gaps',
            status: 'COMPLETED',
            startedAtUtc: '09:15:03',
            completedAtUtc: '09:15:10',
            durationMs: 7000,
            confidenceScore: 0.95,
            summary: 'Sampled 53 document scans. Identified contrast degradation in lower quadrant.',
            artifactsProduced: ['scan_histograms.parquet', 'noise_profile.json'],
            evidenceCount: 53,
        },
        {
            stage: 'PLAN',
            label: 'Adaptive Planning',
            status: 'COMPLETED',
            startedAtUtc: '09:15:10',
            completedAtUtc: '09:15:18',
            durationMs: 8000,
            confidenceScore: 0.96,
            summary: 'Formulated Bayesian hyperparameter DAG for adaptive thresholding.',
            artifactsProduced: ['execution_dag.json', 'parameter_bounds.json'],
            evidenceCount: 18,
        },
        {
            stage: 'EXECUTE',
            label: 'Autonomous Execution',
            status: 'COMPLETED',
            startedAtUtc: '09:15:18',
            completedAtUtc: '09:22:40',
            durationMs: 442000,
            confidenceScore: 0.97,
            summary: 'Ran closed-loop Bayesian optimization across 10 evaluation trials.',
            artifactsProduced: ['trial_results.csv', 'model_weights.bin'],
            evidenceCount: 10,
        },
        {
            stage: 'REFLECT',
            label: 'Empirical Reflection',
            status: 'ACTIVE',
            startedAtUtc: '09:22:40',
            durationMs: 12000,
            confidenceScore: 0.972,
            summary: 'Cross-validating predictions against holdout dataset. Calculating p-values and effect size.',
            artifactsProduced: ['reflection_matrix.json'],
            evidenceCount: 53,
        },
        {
            stage: 'CRITIQUE',
            label: 'Multi-Agent Critique',
            status: 'PENDING',
            summary: 'Reviewer and Governance agents audit decision boundaries and verify zero bias.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
        {
            stage: 'LEARN',
            label: 'Invariant Learning',
            status: 'PENDING',
            summary: 'Extract generalized OCR contrast heuristics for thermal paper types.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
        {
            stage: 'UPDATE_MEMORY',
            label: 'Memory Consolidation',
            status: 'PENDING',
            summary: 'Update Pareto optimal success store and reinforce long-term decay weights.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
        {
            stage: 'IMPROVE_PLAN',
            label: 'Plan Refinement',
            status: 'PENDING',
            summary: 'Re-calibrate upcoming batch execution strategies based on empirical learnings.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
        {
            stage: 'CONTINUE',
            label: 'Autonomous Progression',
            status: 'PENDING',
            summary: 'Advance to next document cohort without human intervention.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
        {
            stage: 'STOP',
            label: 'Goal Satisfied',
            status: 'PENDING',
            summary: 'Mission terminates when statistical power >= 0.80 and confidence >= 95%.',
            artifactsProduced: [],
            evidenceCount: 0,
        },
    ],
    currentCognitionStage: 'REFLECT',
    agentTeam: [
        {
            agentId: 'agent_planner',
            name: 'Planner Agent',
            role: 'PLANNER',
            state: 'IDLE',
            currentGoal: 'Formulate adaptive execution graph',
            thinkingDurationMs: 420,
            lastDecisionSummary: 'Selected 6-node DAG with contrast pre-filter',
            confidence: 0.96,
            tokensProcessed: 18400,
            queueSize: 0,
            heartbeatUtc: '09:23:12',
        },
        {
            agentId: 'agent_evidence',
            name: 'Evidence Agent',
            role: 'EVIDENCE',
            state: 'OBSERVING',
            currentGoal: 'Verifying 53 empirical observation digests',
            thinkingDurationMs: 890,
            lastDecisionSummary: 'Cryptographic SHA-256 matches verified',
            confidence: 0.99,
            tokensProcessed: 24300,
            queueSize: 2,
            heartbeatUtc: '09:23:14',
        },
        {
            agentId: 'agent_memory',
            name: 'Memory Agent',
            role: 'MEMORY',
            state: 'IDLE',
            currentGoal: 'Indexing Pareto optimal hyperparameter weights',
            thinkingDurationMs: 310,
            lastDecisionSummary: 'Recalled 18 previous invoice missions',
            confidence: 0.94,
            tokensProcessed: 12100,
            queueSize: 0,
            heartbeatUtc: '09:23:10',
        },
        {
            agentId: 'agent_exec',
            name: 'Execution Agent',
            role: 'EXTRACTION',
            state: 'IDLE',
            currentGoal: 'Completed Bayesian optimization trials',
            thinkingDurationMs: 1450,
            lastDecisionSummary: 'Optimal contrast scale x* = 0.6800',
            confidence: 0.97,
            tokensProcessed: 68500,
            queueSize: 0,
            heartbeatUtc: '09:23:15',
        },
        {
            agentId: 'agent_reflection',
            name: 'Reflection Agent',
            role: 'REFLECTION',
            state: 'THINKING',
            currentGoal: 'Calculating empirical p-values & statistical power',
            thinkingDurationMs: 2100,
            lastDecisionSummary: 'Evaluating 95% confidence intervals',
            confidence: 0.972,
            tokensProcessed: 31200,
            queueSize: 1,
            heartbeatUtc: '09:23:15',
        },
        {
            agentId: 'agent_stats',
            name: 'Statistics Agent',
            role: 'STATISTICS',
            state: 'THINKING',
            currentGoal: 'Sample size verification (n=53 >= 48 threshold)',
            thinkingDurationMs: 180,
            lastDecisionSummary: 'Statistical power verified at 0.84',
            confidence: 0.985,
            tokensProcessed: 15400,
            queueSize: 0,
            heartbeatUtc: '09:23:14',
        },
        {
            agentId: 'agent_governance',
            name: 'Governance Agent',
            role: 'GOVERNANCE',
            state: 'VERIFYING',
            currentGoal: 'Auditing SLSA Level 3+ digital signatures',
            thinkingDurationMs: 560,
            lastDecisionSummary: 'Zero PII leakages detected; policy compliant',
            confidence: 0.999,
            tokensProcessed: 9800,
            queueSize: 0,
            heartbeatUtc: '09:23:13',
        },
        {
            agentId: 'agent_publication',
            name: 'Publication Agent',
            role: 'PUBLICATION',
            state: 'IDLE',
            currentGoal: 'Preparing LaTeX research table artifact',
            thinkingDurationMs: 640,
            lastDecisionSummary: 'Drafted Section 4 empirical diff',
            confidence: 0.95,
            tokensProcessed: 14200,
            queueSize: 0,
            heartbeatUtc: '09:23:09',
        },
        {
            agentId: 'agent_reviewer',
            name: 'Reviewer Agent',
            role: 'REVIEWER',
            state: 'IDLE',
            currentGoal: 'Awaiting reflection completion for peer review',
            thinkingDurationMs: 400,
            lastDecisionSummary: 'Approved initial experimental protocol',
            confidence: 0.96,
            tokensProcessed: 11000,
            queueSize: 0,
            heartbeatUtc: '09:23:11',
        },
        {
            agentId: 'agent_coord',
            name: 'Coordinator Agent',
            role: 'COORDINATOR',
            state: 'THINKING',
            currentGoal: 'Harmonizing inter-agent consensus and thought streams',
            thinkingDurationMs: 250,
            lastDecisionSummary: 'Deliberation consensus = 0.97',
            confidence: 0.97,
            tokensProcessed: 42000,
            queueSize: 3,
            heartbeatUtc: '09:23:15',
        },
    ],
    thoughtStream: [
        {
            id: 'msg_01',
            agentRole: 'PLANNER',
            agentName: 'Planner Agent',
            timestampUtc: '09:15:02',
            thoughtType: 'DELIBERATION',
            content: 'Deconstructing goal into measurable subgoals: OCR Preprocess -> Layout Parse -> Field Extract -> SLSA Proof.',
            confidence: 0.98,
        },
        {
            id: 'msg_02',
            agentRole: 'MEMORY',
            agentName: 'Memory Agent',
            timestampUtc: '09:15:05',
            thoughtType: 'MEMORY_RECALL',
            content: 'Retrieved 18 historical missions with low contrast thermal scans. Recalled that adaptive binarization yields +3.1% precision.',
            confidence: 0.94,
            referencedArtifactId: 'mem_inv_04',
        },
        {
            id: 'msg_03',
            agentRole: 'EVIDENCE',
            agentName: 'Evidence Agent',
            timestampUtc: '09:15:07',
            thoughtType: 'EVIDENCE_DISCOVERY',
            content: 'Discovered 53 ground truth annotated sample patches with valid SHA-256 digests in storage ledger.',
            confidence: 0.99,
        },
        {
            id: 'msg_04',
            agentRole: 'GOVERNANCE',
            agentName: 'Governance Agent',
            timestampUtc: '09:15:08',
            thoughtType: 'DELIBERATION',
            content: 'Audited execution boundaries: Zero-Fabrication enforcement active. No synthetic data hallucination allowed.',
            confidence: 1.0,
        },
        {
            id: 'msg_05',
            agentRole: 'COORDINATOR',
            agentName: 'Coordinator Agent',
            timestampUtc: '09:15:10',
            thoughtType: 'CONSENSUS',
            content: 'Consensus achieved across all 10 agents (Score: 0.97). Dispatched mission execution DAG.',
            confidence: 0.97,
        },
        {
            id: 'msg_06',
            agentRole: 'REFLECTION',
            agentName: 'Reflection Agent',
            timestampUtc: '09:22:45',
            thoughtType: 'DELIBERATION',
            content: 'Bayesian trial completed: Optimal hyperparameter x*=0.6800 achieved F1=0.9796 across 53 samples.',
            confidence: 0.972,
        },
    ],
    dagNodes: [
        {
            id: 'node_goal',
            label: 'Goal: Optimize Invoice Extraction',
            nodeType: 'GOAL',
            status: 'COMPLETED',
            assignedAgent: 'COORDINATOR',
            dependencies: [],
            inputs: ['User Objective String'],
            outputs: ['Validated Goal Model'],
            runtimeSeconds: 3,
            retryCount: 0,
            artifactsProduced: ['goal_spec.json'],
            sha256Digest: '5fc03ae31fe41fce3f73ffab2fec820f46c3ef6be0b9efc7d7e63459c04297a7',
        },
        {
            id: 'node_preprocess',
            label: 'Task 1: Adaptive Contrast & Noise Filter',
            nodeType: 'TASK',
            status: 'COMPLETED',
            assignedAgent: 'PLANNER',
            dependencies: ['node_goal'],
            inputs: ['Raw Scans', 'Histogram Profiles'],
            outputs: ['Binarized Scans'],
            runtimeSeconds: 14,
            retryCount: 0,
            artifactsProduced: ['binarized_scans.zip'],
            sha256Digest: 'a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0',
        },
        {
            id: 'node_bayesian_opt',
            label: 'Execution: Bayesian Hyperparameter Search',
            nodeType: 'EXECUTION_UNIT',
            status: 'COMPLETED',
            assignedAgent: 'EXTRACTION',
            dependencies: ['node_preprocess'],
            inputs: ['Binarized Scans', 'Parameter Bounds'],
            outputs: ['Optimal Parameter x*', 'F1 Loss Trajectory'],
            runtimeSeconds: 428,
            retryCount: 0,
            artifactsProduced: ['bayesian_trials.csv', 'opt_weights.bin'],
            sha256Digest: 'de91fecc18afecdeb923a10248c823019842bcdafe2391038592038102394812',
        },
        {
            id: 'node_reflect_stat',
            label: 'Reflection: Statistical Power & Confidence Bounds',
            nodeType: 'TASK',
            status: 'IN_PROGRESS',
            assignedAgent: 'REFLECTION',
            dependencies: ['node_bayesian_opt'],
            inputs: ['Trial Results', 'Holdout Annotations'],
            outputs: ['Confidence Interval [0.949, 0.995]', 'p-value (0.0012)'],
            runtimeSeconds: 12,
            retryCount: 0,
            artifactsProduced: ['stat_power_report.json'],
            sha256Digest: 'e0cc60bdbae9aa64...pending',
        },
        {
            id: 'node_slsa_proof',
            label: 'Evidence: SLSA Level 3+ Lineage Certification',
            nodeType: 'EVIDENCE',
            status: 'PENDING',
            assignedAgent: 'GOVERNANCE',
            dependencies: ['node_reflect_stat'],
            inputs: ['Execution Artifact Digests'],
            outputs: ['Cryptographic Attestation'],
            retryCount: 0,
            artifactsProduced: [],
        },
        {
            id: 'node_publication',
            label: 'Publication: Living Research Table Diff',
            nodeType: 'PUBLICATION',
            status: 'PENDING',
            assignedAgent: 'PUBLICATION',
            dependencies: ['node_slsa_proof'],
            inputs: ['Verified Metrics', 'Provenance Ledger'],
            outputs: ['Updated Publication Artifact'],
            retryCount: 0,
            artifactsProduced: [],
        },
    ],
    decisions: [
        {
            id: 'dec_contrast_01',
            timestampUtc: '09:15:12',
            decisionTitle: 'Approve Adaptive Contrast Optimization Strategy',
            reasoning: 'Thermal invoice scans exhibit severe gradient fading in footer sections. Standard global Otsu thresholding resulted in 14.2% character loss in historical runs.',
            selectedAction: 'ADAPTIVE_LOCAL_CONTRAST_BOOST',
            confidenceScore: 0.972,
            supportingEvidenceSummary: 'Verified against 53 ground truth observation patches across 18 previous thermal scan missions.',
            evidenceCount: 53,
            alternativesConsidered: [
                {
                    actionName: 'Global Otsu Binarization',
                    score: 0.74,
                    rejectedReason: 'Poor contrast uniformity on shaded backgrounds; caused missing line item decimals.',
                },
                {
                    actionName: 'Fixed Scale Histogram Equalization',
                    score: 0.81,
                    rejectedReason: 'Amplified background sensor noise on scan margins.',
                },
            ],
            tradeoffs: 'Increases preprocessing latency by 12ms per page in exchange for +3.1% macro F1 accuracy improvement.',
            expectedOutcome: 'Achieves >=97.0% field extraction recall with zero loss of invoice tax identifiers.',
            riskVectors: [
                { dimension: 'ACCURACY', score: 0.04, severity: 'LOW' },
                { dimension: 'LATENCY', score: 0.12, severity: 'LOW' },
                { dimension: 'SAFETY', score: 0.01, severity: 'LOW' },
                { dimension: 'SECURITY', score: 0.01, severity: 'LOW' },
                { dimension: 'BIAS', score: 0.02, severity: 'LOW' },
                { dimension: 'COST', score: 0.08, severity: 'LOW' },
                { dimension: 'OVERFITTING', score: 0.05, severity: 'LOW' },
                { dimension: 'INFRASTRUCTURE', score: 0.03, severity: 'LOW' },
                { dimension: 'DATASET_SHIFT', score: 0.06, severity: 'LOW' },
            ],
            overallRisk: 0.046,
            estimatedBenefitUsd: 1450.00,
            estimatedCostUsd: 0.04,
            estimatedRuntimeMs: 140,
            requiresHumanReview: false,
            isHumanOverridden: false,
        },
        {
            id: 'dec_sample_size_02',
            timestampUtc: '09:15:16',
            decisionTitle: 'Enforce Statistical Power Sample Size Threshold (n >= 48)',
            reasoning: 'According to power equation n >= 2((z_alpha + z_beta)/ES)^2, achieving power 0.80 at alpha=0.05 for effect size ES=0.40 requires minimum 48 independent observations.',
            selectedAction: 'ACQUIRE_53_INVOICE_OBSERVATIONS',
            confidenceScore: 0.985,
            supportingEvidenceSummary: 'Calculated by Statistics Agent with alpha=0.05, beta=0.20.',
            evidenceCount: 53,
            alternativesConsidered: [
                {
                    actionName: 'Rapid Sample (n=15)',
                    score: 0.52,
                    rejectedReason: 'Violates statistical power requirements; risk of type II error > 40%.',
                },
            ],
            tradeoffs: 'Consumes $0.40 extra compute budget to guarantee publication-grade certainty.',
            expectedOutcome: 'Guarantees 95% confidence interval width <= 4.6% margin of error.',
            riskVectors: [
                { dimension: 'ACCURACY', score: 0.02, severity: 'LOW' },
                { dimension: 'COST', score: 0.10, severity: 'LOW' },
            ],
            overallRisk: 0.035,
            estimatedBenefitUsd: 800.00,
            estimatedCostUsd: 0.40,
            estimatedRuntimeMs: 2500,
            requiresHumanReview: false,
            isHumanOverridden: false,
        },
    ],
    evidenceItems: [
        {
            id: 'ev_sroie_53',
            title: 'Ground Truth Invoice Validation Dataset',
            sourceType: 'DATASET',
            origin: 'sroie_invoices_v2/holdout_batch_q3',
            timestampUtc: '2026-09-09T09:15:00Z',
            sha256Digest: 'de91fecc18afecdeb923a10248c823019842bcdafe2391038592038102394812',
            verificationStatus: 'CRYPTOGRAPHICALLY_VERIFIED',
            confidenceContribution: 0.38,
            sampleCount: 53,
            slsaLevel: 'SLSA_LEVEL_3',
        },
        {
            id: 'ev_bayes_trials',
            title: 'Bayesian Optimization Convergence Trials',
            sourceType: 'EXPERIMENT',
            origin: 'research_validation/optimization/bayesian_optimizer.py',
            timestampUtc: '2026-09-09T09:22:40Z',
            sha256Digest: 'a1b4b9b940cf5a73e0cc60bdbae9aa64...9653dd0a',
            verificationStatus: 'CRYPTOGRAPHICALLY_VERIFIED',
            confidenceContribution: 0.42,
            sampleCount: 10,
            slsaLevel: 'SLSA_LEVEL_3',
        },
        {
            id: 'ev_regression_audit',
            title: 'Multi-Dimensional Drift & Regression Audit',
            sourceType: 'REGRESSION_TEST',
            origin: 'research_validation/regression/regression_detector.py',
            timestampUtc: '2026-09-09T09:22:45Z',
            sha256Digest: '8b5cf610b98134d399fbbf24fb923cf87171e11d48d97706dc262638bdf8e0',
            verificationStatus: 'CRYPTOGRAPHICALLY_VERIFIED',
            confidenceContribution: 0.172,
            sampleCount: 100,
            slsaLevel: 'SLSA_LEVEL_4',
        },
    ],
    memoryEntries: [
        {
            id: 'mem_pareto_01',
            store: 'SUCCESS_PARETO',
            title: 'Optimal Contrast Factor for Low-Light Scans',
            summary: 'Parameter x*=0.6800 achieves Pareto optimality between character segmentation accuracy and edge artifact noise.',
            createdAtUtc: '2026-09-08T18:00:00Z',
            lastRecalledUtc: '2026-09-09T09:15:05Z',
            recallCount: 23,
            retentionWeight: 0.94,
            similarityScore: 0.91,
            decayHalfLifeDays: 30,
            importanceRating: 5,
            linkedMissionIds: ['mission_9941', 'mission_autocog_799784'],
            sha256Proof: '799784cdbbf34a569e812ba70c3dd79c',
        },
        {
            id: 'mem_fail_02',
            store: 'FAILURE_PATTERN',
            title: 'Failure Mode: Global Thresholding on Watermarks',
            summary: 'Global Otsu causes 100% loss of company registration numbers when watermark opacity exceeds 0.25.',
            createdAtUtc: '2026-09-05T11:00:00Z',
            lastRecalledUtc: '2026-09-09T09:15:06Z',
            recallCount: 14,
            retentionWeight: 0.88,
            similarityScore: 0.85,
            decayHalfLifeDays: 45,
            importanceRating: 4,
            linkedMissionIds: ['mission_8812'],
            sha256Proof: 'a1b2c3d4e5f6',
        },
        {
            id: 'mem_episodic_03',
            store: 'EPISODIC',
            title: 'Prior Mission Cycle: Invoice Table Segmentation',
            summary: 'Executed 12 trials on receipts; established baseline CER at 0.042.',
            createdAtUtc: '2026-09-08T20:30:00Z',
            lastRecalledUtc: '2026-09-09T09:15:05Z',
            recallCount: 6,
            retentionWeight: 0.96,
            similarityScore: 0.89,
            decayHalfLifeDays: 14,
            importanceRating: 4,
            linkedMissionIds: ['mission_9941'],
            sha256Proof: 'c88129762cf59b023455a713400dc4d2a46357e89049ab4cb964f9c0a513dfc3',
        },
    ],
    confidenceData: {
        currentConfidence: 0.972,
        targetConfidence: 0.950,
        stoppingThreshold: 0.950,
        sampleSize: 53,
        marginOfError: 0.023,
        confidenceInterval: [0.949, 0.995],
        statisticalPower: 0.84,
        pValue: 0.0012,
        evidenceCount: 53,
        missingEvidenceCount: 0,
        uncertaintySources: [
            {
                source: 'Sensor noise on faded thermal paper',
                impactPercentage: 1.8,
                mitigationStatus: 'MITIGATED (Adaptive contrast filter)',
            },
            {
                source: 'Font variance in international VAT numbers',
                impactPercentage: 1.0,
                mitigationStatus: 'ACTIVE_OBSERVATION (Dual regex validator)',
            },
        ],
        whyConfidenceChanged: 'Confidence increased from 0.941 to 0.972 after Bayesian trials converged and sample size reached n=53 (exceeding minimum n=48 threshold).',
        trendHistory: [
            { timestamp: '09:15', confidence: 0.880, sampleSize: 10 },
            { timestamp: '09:17', confidence: 0.915, sampleSize: 25 },
            { timestamp: '09:20', confidence: 0.941, sampleSize: 40 },
            { timestamp: '09:23', confidence: 0.972, sampleSize: 53 },
        ],
    },
    humanAuditLogs: [
        {
            id: 'audit_01',
            timestampUtc: '09:15:00',
            action: 'APPROVE',
            triggeredBy: 'System Administrator (Auto-Approved under Policy RMF-3)',
            reason: 'Mission parameters within standard operating bounds.',
            resultingMissionState: 'ACTIVE',
            auditSha256Receipt: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        },
    ],
    isPaused: false,
    isSimulatingLive: true,
};
