/**
 * Realistic Mock Initial Data for DocuTask Agent AI Coworker Workspace
 */

import type {
  ChatMessage,
  AgentInboxItem,
  HumanFeedbackItem,
  TimelineExecutionEvent,
  MemoryCausalNode,
  ConfidenceConstituent,
  ReplaySnapshot,
  WorkspaceTaskItem,
} from '../types/workspace';

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'msg_01',
    sender: 'AI_COWORKER',
    agentRole: 'COORDINATOR',
    timestampUtc: '09:15:00',
    text: "Hello! I am DocuTask Agent, your autonomous document coworker. I've initiated our Q3 invoice processing mission. We are actively aiming for >=95% statistical confidence with zero hallucination.",
    suggestedQuickActions: [
      'Improve invoice extraction',
      'Explain why confidence changed',
      'Retry with adaptive contrast',
      'View memory causal graph',
    ],
  },
  {
    id: 'msg_02',
    sender: 'HUMAN',
    timestampUtc: '09:15:20',
    text: 'Can you improve invoice extraction on low-contrast thermal scans?',
  },
  {
    id: 'msg_03',
    sender: 'AI_COWORKER',
    agentRole: 'PLANNER',
    timestampUtc: '09:15:24',
    text: 'I analyzed our historical failure memory and identified that standard binarization loses ~14% of VAT numbers on faded paper. I adapted our DAG to inject an Adaptive Local Contrast Filter (x*=0.6800).',
    actionTaken: 'DAG_MUTATION: INJECT_ADAPTIVE_PREPROCESSOR',
    proposedPlanUpdate: [
      'Task 1: Adaptive Contrast & Noise Filter (Assigned: Planner Agent)',
      'Task 2: Bayesian Hyperparameter Search (Assigned: Execution Agent)',
      'Task 3: Statistical Power Audit (Assigned: Statistics Agent)',
    ],
    confidenceScore: 0.972,
    suggestedQuickActions: ['Approve plan adaptation', 'Inspect risk vectors', 'Run live benchmark'],
  },
];

export const initialAgentInbox: AgentInboxItem[] = [
  {
    agentRole: 'PLANNER',
    agentName: 'Planner Agent',
    currentTask: 'Formulate adaptive execution graph',
    workingOn: 'Balancing DAG dependency depth with latency SLAs',
    producedCount: 6,
    confidence: 0.96,
    etaSeconds: 4,
    status: 'ONLINE',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm1', fromRole: 'COORDINATOR', timestampUtc: '09:15:02', body: 'Please decompose new thermal scan objective.' },
      { id: 'm2', fromRole: 'MEMORY', timestampUtc: '09:15:05', body: 'Thermal scan contrast weights available.' },
    ],
  },
  {
    agentRole: 'EVIDENCE',
    agentName: 'Evidence Agent',
    currentTask: 'Auditing 53 empirical observation patches',
    workingOn: 'Validating SHA-256 digests against SROIE ground truth',
    producedCount: 53,
    confidence: 0.99,
    etaSeconds: 2,
    status: 'EXECUTING',
    unreadMessagesCount: 1,
    recentMessages: [
      { id: 'm3', fromRole: 'STATISTICS', timestampUtc: '09:15:08', body: 'Sample size threshold n=53 verified.' },
    ],
  },
  {
    agentRole: 'MEMORY',
    agentName: 'Memory Agent',
    currentTask: 'Indexing Pareto optimal hyperparameter weights',
    workingOn: 'Decay retention consolidation (R = e^(-lambda * dt))',
    producedCount: 18,
    confidence: 0.94,
    etaSeconds: 0,
    status: 'ONLINE',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm4', fromRole: 'PLANNER', timestampUtc: '09:15:04', body: 'Found 18 previous invoice missions.' },
    ],
  },
  {
    agentRole: 'EXTRACTION',
    agentName: 'Execution Agent',
    currentTask: 'Closed-loop Bayesian OCR tuning',
    workingOn: 'Optimal contrast scale trial #10 of 10',
    producedCount: 10,
    confidence: 0.97,
    etaSeconds: 8,
    status: 'THINKING',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm5', fromRole: 'PLANNER', timestampUtc: '09:15:18', body: 'Execution units dispatched.' },
    ],
  },
  {
    agentRole: 'REFLECTION',
    agentName: 'Reflection Agent',
    currentTask: 'Cross-validating 10-fold holdout predictions',
    workingOn: 'Computing empirical effect size & standard error',
    producedCount: 10,
    confidence: 0.972,
    etaSeconds: 5,
    status: 'THINKING',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm6', fromRole: 'STATISTICS', timestampUtc: '09:22:42', body: 'F1 verified at 0.9796.' },
    ],
  },
  {
    agentRole: 'STATISTICS',
    agentName: 'Statistics Agent',
    currentTask: 'Sample size & power verification',
    workingOn: 'Power calculation: n=53 >= 48 required (Power=0.84)',
    producedCount: 4,
    confidence: 0.985,
    etaSeconds: 1,
    status: 'ONLINE',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm7', fromRole: 'GOVERNANCE', timestampUtc: '09:23:00', body: 'Confidence bounds approved.' },
    ],
  },
  {
    agentRole: 'GOVERNANCE',
    agentName: 'Governance Agent',
    currentTask: 'SLSA Level 3+ digital signature audit',
    workingOn: 'Verifying zero unredacted PII in output streams',
    producedCount: 3,
    confidence: 0.999,
    etaSeconds: 0,
    status: 'ONLINE',
    unreadMessagesCount: 0,
    recentMessages: [
      { id: 'm8', fromRole: 'COORDINATOR', timestampUtc: '09:15:10', body: 'Policy RMF-3 compliance check passed.' },
    ],
  },
  {
    agentRole: 'COORDINATOR',
    agentName: 'Coordinator Agent',
    currentTask: 'Harmonizing inter-agent consensus and thought streams',
    workingOn: 'Orchestrating live reflection -> critique transition',
    producedCount: 12,
    confidence: 0.97,
    etaSeconds: 1,
    status: 'ONLINE',
    unreadMessagesCount: 2,
    recentMessages: [
      { id: 'm9', fromRole: 'REFLECTION', timestampUtc: '09:22:45', body: 'Trial results ready for review.' },
    ],
  },
];

export const initialHumanFeedbackItems: HumanFeedbackItem[] = [
  {
    id: 'fb_01',
    documentId: 'INV_THERMAL_984.pdf',
    fieldName: 'TaxRegistrationNumber',
    extractedValue: 'VAT-98210-A',
    correctedValue: 'VAT-98210-AX',
    confidenceWas: 0.81,
    submittedAtUtc: '09:18:22',
    status: 'CONVERTED_TO_MEMORY',
    appliedLessonSummary: 'Learned: Suffix letters on shaded watermarks require localized adaptive contrast.',
  },
  {
    id: 'fb_02',
    documentId: 'RECEIPT_OIL_12.jpg',
    fieldName: 'TotalAmount',
    extractedValue: '$140.00',
    correctedValue: '$140.80',
    confidenceWas: 0.74,
    submittedAtUtc: '09:20:10',
    status: 'CONVERTED_TO_RULE',
    appliedLessonSummary: 'Rule created: Always cross-check subtotal + tax = total to avoid rounded cents errors.',
  },
];

export const initialTimelineEvents: TimelineExecutionEvent[] = [
  {
    id: 'tl_01',
    timestampUtc: '09:15:00',
    timeDisplay: '09:15:00',
    agentRole: 'COORDINATOR',
    agentName: 'Coordinator Agent',
    eventTitle: 'Mission Initiated',
    eventDescription: 'Objective: Extract line items and tax totals from noisy utility scans with >=95% confidence.',
    stageName: 'GOAL',
    confidenceScore: 0.99,
  },
  {
    id: 'tl_02',
    timestampUtc: '09:15:04',
    timeDisplay: '09:15:04',
    agentRole: 'PLANNER',
    agentName: 'Planner Agent',
    eventTitle: 'Created 6 Subtasks & Compiled DAG',
    eventDescription: 'Topologically sorted preprocessing, Bayesian tuning, and SLSA validation stages.',
    stageName: 'PLAN',
    confidenceScore: 0.96,
    producedArtifact: 'execution_dag.json',
  },
  {
    id: 'tl_03',
    timestampUtc: '09:15:10',
    timeDisplay: '09:15:10',
    agentRole: 'EVIDENCE',
    agentName: 'Evidence Agent',
    eventTitle: 'Discovered 53 Ground Truth Observations',
    eventDescription: 'Loaded holdout annotation digests from SROIE V2 repository.',
    stageName: 'OBSERVE',
    confidenceScore: 0.99,
    producedArtifact: 'scan_histograms.parquet',
  },
  {
    id: 'tl_04',
    timestampUtc: '09:22:40',
    timeDisplay: '09:22:40',
    agentRole: 'EXTRACTION',
    agentName: 'Execution Agent',
    eventTitle: 'Bayesian Hyperparameter Search Complete',
    eventDescription: 'Evaluated 10 trials; optimal scale x*=0.6800 achieved F1=0.9796.',
    stageName: 'EXECUTE',
    confidenceScore: 0.97,
    producedArtifact: 'trial_results.csv',
  },
  {
    id: 'tl_05',
    timestampUtc: '09:22:45',
    timeDisplay: '09:22:45',
    agentRole: 'REFLECTION',
    agentName: 'Reflection Agent',
    eventTitle: 'Empirical Reflection Active',
    eventDescription: 'Statistical power verified at 0.84 with sample size n=53 (stopping power target exceeded).',
    stageName: 'REFLECT',
    confidenceScore: 0.972,
    producedArtifact: 'stat_power_report.json',
  },
];

export const initialMemoryCausalNodes: MemoryCausalNode[] = [
  {
    id: 'node_doc',
    label: 'Thermal Invoice Scans',
    nodeType: 'DOCUMENT',
    description: 'Degraded receipts with fading ink on thermal paper rolls.',
    connections: ['node_failure'],
    retentionScore: 0.98,
  },
  {
    id: 'node_failure',
    label: 'OCR Failure Mode: Low Contrast Loss',
    nodeType: 'FAILURE_MODE',
    description: 'Global thresholding loses decimal points and VAT suffixes (-14.2% F1).',
    connections: ['node_reflection'],
    metricImpact: '-14.2% F1',
    retentionScore: 0.91,
  },
  {
    id: 'node_reflection',
    label: 'Reflection: Spatial Contrast Invariance',
    nodeType: 'REFLECTION',
    description: 'Identified that contrast loss is localized to document quadrants.',
    connections: ['node_lesson'],
    retentionScore: 0.94,
  },
  {
    id: 'node_lesson',
    label: 'Lesson Learned: Adaptive Kernel Binarization',
    nodeType: 'LESSON_LEARNED',
    description: 'Tuning kernel size with Bayesian optimization preserves decimal points.',
    connections: ['node_applied'],
    metricImpact: '+3.1% F1 Gain',
    retentionScore: 0.96,
  },
  {
    id: 'node_applied',
    label: 'Invariant Applied: Optimal Scale x*=0.6800',
    nodeType: 'INVARIANT_APPLIED',
    description: 'Automated policy injected into live DAG; verified on 53 samples.',
    connections: [],
    metricImpact: '97.2% Final Confidence',
    retentionScore: 0.99,
  },
];

export const initialConfidenceConstituents: ConfidenceConstituent[] = [
  {
    name: 'OCR Core Engine & Adaptive Preprocessor',
    category: 'OCR_ENGINE',
    contributionPercentage: 32,
    confidenceScore: 0.982,
    sampleSize: 53,
    status: 'VERIFIED',
    description: 'Empirical character accuracy across 53 holdout document patches.',
  },
  {
    name: 'Independent Benchmark Evidence (SROIE)',
    category: 'EVIDENCE_OBSERVATION',
    contributionPercentage: 24,
    confidenceScore: 0.990,
    sampleSize: 53,
    status: 'VERIFIED',
    description: 'Cross-validated against certified ground truth JSON annotations.',
  },
  {
    name: 'Long-Term Memory & Pareto Frontier',
    category: 'MEMORY_RECALL',
    contributionPercentage: 18,
    confidenceScore: 0.940,
    sampleSize: 18,
    status: 'VERIFIED',
    description: 'Recalled 18 prior thermal invoice optimization runs.',
  },
  {
    name: '10-Agent Deliberation & Consensus',
    category: 'MULTI_AGENT_CONSENSUS',
    contributionPercentage: 12,
    confidenceScore: 0.970,
    status: 'VERIFIED',
    description: 'Planner, Governance, Memory, and Reviewer consensus agreement score.',
  },
  {
    name: 'Statistical Power & Error Bounds',
    category: 'VALIDATION',
    contributionPercentage: 11,
    confidenceScore: 0.985,
    sampleSize: 53,
    status: 'VERIFIED',
    description: 'Sample size n=53 satisfies power 0.80 effect size threshold.',
  },
  {
    name: 'Human-in-the-Loop Feedback & Verified Rules',
    category: 'HUMAN_FEEDBACK',
    contributionPercentage: 3,
    confidenceScore: 0.995,
    sampleSize: 2,
    status: 'VERIFIED',
    description: 'Verified operator corrections distilled into immutable rules.',
  },
];

export const initialReplaySnapshots: ReplaySnapshot[] = [
  {
    stepIndex: 1,
    totalSteps: 5,
    timestampUtc: '09:15:00',
    stageName: 'GOAL',
    activeAgent: 'COORDINATOR',
    thoughtTitle: 'Goal Understanding & Constraint Parsing',
    thoughtContent: 'Parsed user objective. Normalized target F1 metric to >= 95%.',
    currentConfidence: 0.88,
    completedTasksCount: 0,
    activeDecisionTitle: 'Normalized Objective Intent Model',
  },
  {
    stepIndex: 2,
    totalSteps: 5,
    timestampUtc: '09:15:04',
    stageName: 'PLAN',
    activeAgent: 'PLANNER',
    thoughtTitle: 'Formulated 6-Node Adaptive Execution DAG',
    thoughtContent: 'Recalled memory of thermal scan degradation. Injected adaptive contrast preprocessing.',
    currentConfidence: 0.915,
    completedTasksCount: 1,
    activeDecisionTitle: 'Approve Adaptive Contrast Optimization Strategy',
    memoryAccessTitle: 'Recalled 18 Thermal Invoice Missions',
  },
  {
    stepIndex: 3,
    totalSteps: 5,
    timestampUtc: '09:15:10',
    stageName: 'OBSERVE',
    activeAgent: 'EVIDENCE',
    thoughtTitle: 'Acquired 53 Ground Truth Observations',
    thoughtContent: 'Sampled 53 document scans. Verified SHA-256 integrity digests.',
    currentConfidence: 0.941,
    completedTasksCount: 2,
    activeDecisionTitle: 'Enforce Statistical Power Sample Size Threshold (n >= 48)',
  },
  {
    stepIndex: 4,
    totalSteps: 5,
    timestampUtc: '09:22:40',
    stageName: 'EXECUTE',
    activeAgent: 'EXTRACTION',
    thoughtTitle: 'Closed-Loop Bayesian Trials Completed',
    thoughtContent: 'Optimal parameter x*=0.6800 converged with loss < 0.0204.',
    currentConfidence: 0.965,
    completedTasksCount: 4,
    activeDecisionTitle: 'Optimal Contrast Factor Selected',
  },
  {
    stepIndex: 5,
    totalSteps: 5,
    timestampUtc: '09:22:45',
    stageName: 'REFLECT',
    activeAgent: 'REFLECTION',
    thoughtTitle: 'Empirical Reflection & Confidence Target Reached',
    thoughtContent: '95% Confidence Interval [0.949, 0.995] verified with p=0.0012.',
    currentConfidence: 0.972,
    completedTasksCount: 5,
    activeDecisionTitle: 'Goal Confidence Target Satisfied',
  },
];

export const initialWorkspaceTasks: WorkspaceTaskItem[] = [
  {
    id: 'task_01',
    title: 'Adaptive Contrast & Noise Filtering',
    category: 'PREPROCESS',
    status: 'DONE',
    assignedAgentRole: 'PLANNER',
    priority: 'HIGH',
    progressPercent: 100,
    estimatedRuntimeMs: 14000,
    producedArtifact: 'binarized_scans.zip',
  },
  {
    id: 'task_02',
    title: 'Bayesian Hyperparameter Search (x*)',
    category: 'EXTRACTION',
    status: 'DONE',
    assignedAgentRole: 'EXTRACTION',
    priority: 'CRITICAL',
    progressPercent: 100,
    estimatedRuntimeMs: 428000,
    producedArtifact: 'trial_results.csv',
  },
  {
    id: 'task_03',
    title: 'Holdout Cross-Validation & Statistical Power',
    category: 'VALIDATION',
    status: 'IN_PROGRESS',
    assignedAgentRole: 'REFLECTION',
    priority: 'CRITICAL',
    progressPercent: 85,
    estimatedRuntimeMs: 12000,
    producedArtifact: 'stat_power_report.json',
  },
  {
    id: 'task_04',
    title: 'SLSA Level 3+ Digital Signature Attestation',
    category: 'EVIDENCE',
    status: 'TODO',
    assignedAgentRole: 'GOVERNANCE',
    priority: 'HIGH',
    progressPercent: 0,
    estimatedRuntimeMs: 3000,
  },
  {
    id: 'task_05',
    title: 'Entity Reconciliation & Line Item Matching',
    category: 'RECONCILIATION',
    status: 'TODO',
    assignedAgentRole: 'COORDINATOR',
    priority: 'MEDIUM',
    progressPercent: 0,
    estimatedRuntimeMs: 8000,
  },
];
