import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
export const OperationalAnalyticsView = () => {
    const metrics = [
        { label: '30-Day Mean Time Between Failures', value: '720 Hours', change: '+14% vs last mo', status: 'optimal' },
        { label: '30-Day Mean Time To Recovery', value: '45.2 ms', change: '-32% faster', status: 'optimal' },
        { label: 'SLA Budget Adherence Rate', value: '99.98%', change: '+0.04%', status: 'optimal' },
        { label: 'Cumulative Self-Healing Savings', value: '$4,120 USD', change: '85 eng hours saved', status: 'optimal' },
    ];
    const operationalLogs = [
        { timestamp: '2026-09-10 14:20:00', event: 'Gemini 504 Failover', mttr: '45.0 ms', deltaCost: '-$0.0015', result: 'Zero Parity Loss' },
        { timestamp: '2026-09-09 18:12:30', event: 'Redis Circuit Breaker Fallback', mttr: '8.5 ms', deltaCost: '$0.0000', result: 'Zero Read Drop' },
        { timestamp: '2026-09-08 09:45:12', event: 'OCR Worker Sandbox Respawn', mttr: '180.0 ms', deltaCost: '+$0.0001', result: 'Task Resumed' },
        { timestamp: '2026-09-07 22:04:18', event: 'Memory Checkpoint Warm Reload', mttr: '95.0 ms', deltaCost: '$0.0000', result: 'State Restored' },
        { timestamp: '2026-09-06 11:30:44', event: 'DAG Deadlock Branch Prune', mttr: '140.0 ms', deltaCost: '+$0.0003', result: 'Graph Re-synthesized' },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-border/40 pb-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Operational Reliability Analytics" }), _jsx(Badge, { variant: "intelligence", size: "sm", children: "Long-Term Telemetry" })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-1", children: "Historical reliability trends, MTBF expansion curves, autonomous failover efficiencies, and operational cost savings." })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsx(Badge, { variant: "success", size: "md", children: "Operational Uptime: 99.9988%" }) })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-4 gap-4", children: metrics.map((m, idx) => (_jsxs(Card, { className: "p-4 border-border/60 space-y-1", children: [_jsx("div", { className: "text-xs font-semibold text-muted-foreground", children: m.label }), _jsx("div", { className: "text-2xl font-bold font-mono text-foreground mt-1", children: m.value }), _jsx("div", { className: "text-[11px] text-emerald-400 font-semibold mt-1", children: m.change })] }, idx))) }), _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "text-sm font-semibold tracking-wider text-muted-foreground uppercase", children: "Autonomous Self-Healing Event Telemetry" }), _jsx("div", { className: "border border-border/40 rounded-lg overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-xs font-mono", children: [_jsx("thead", { className: "bg-muted/40 text-muted-foreground border-b border-border/40", children: _jsxs("tr", { children: [_jsx("th", { className: "p-2.5 font-medium font-sans", children: "Timestamp (UTC)" }), _jsx("th", { className: "p-2.5 font-medium font-sans", children: "Trigger Event" }), _jsx("th", { className: "p-2.5 font-medium text-right font-sans", children: "Recovery MTTR" }), _jsx("th", { className: "p-2.5 font-medium text-right font-sans", children: "Cost Delta" }), _jsx("th", { className: "p-2.5 font-medium text-center font-sans", children: "Outcome" })] }) }), _jsx("tbody", { className: "divide-y divide-border/20", children: operationalLogs.map((log, idx) => (_jsxs("tr", { className: "hover:bg-muted/20", children: [_jsx("td", { className: "p-2.5 text-muted-foreground", children: log.timestamp }), _jsx("td", { className: "p-2.5 text-foreground font-sans font-semibold", children: log.event }), _jsx("td", { className: "p-2.5 text-right text-blue-400 font-bold", children: log.mttr }), _jsx("td", { className: "p-2.5 text-right text-emerald-400", children: log.deltaCost }), _jsx("td", { className: "p-2.5 text-center font-sans", children: _jsx(Badge, { variant: "success", size: "sm", children: log.result }) })] }, idx))) })] }) })] })] }));
};
