"""Execution Plan Data Model for Autonomous Agent Operating System.

Defines the concrete executable plan produced by the AutonomousPlanner,
including assigned agents, tools, fallback branches, and verification steps.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    SCHEDULED = "SCHEDULED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    MUTATED = "MUTATED"


@dataclass
class PlannedTask:
    """Individual atomic or composite task within an ExecutionPlan."""

    task_id: str
    name: str
    action: str
    assigned_agent: Optional[str] = None
    required_tools: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    input_parameters: Dict[str, Any] = field(default_factory=dict)
    output_key: str = "result"
    status: TaskStatus = TaskStatus.PENDING
    fallback_agent: Optional[str] = None
    fallback_tools: List[str] = field(default_factory=list)
    max_retries: int = 2
    timeout_seconds: float = 30.0
    is_critical: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_ready(self, completed_tasks: set[str]) -> bool:
        """Task is ready if all its dependencies have completed."""
        return all(dep in completed_tasks for dep in self.dependencies)


@dataclass
class FallbackStrategy:
    """Strategy for handling failures of specific tasks or agents."""

    task_id: str
    fallback_action: str  # "RETRY_WITH_ALTERNATIVE_AGENT", "SWITCH_TOOL", "HUMAN_ESCALATION", "SKIP"
    alternative_agent: Optional[str] = None
    alternative_tools: List[str] = field(default_factory=list)
    max_fallback_attempts: int = 2


@dataclass
class ExecutionPlan:
    """Concrete plan generated by the Autonomous Planning Engine."""

    goal_id: str
    plan_id: str = field(default_factory=lambda: f"plan_{uuid.uuid4().hex[:12]}")
    tasks: List[PlannedTask] = field(default_factory=list)
    fallback_strategies: Dict[str, FallbackStrategy] = field(default_factory=dict)
    verification_steps: List[str] = field(default_factory=list)
    estimated_duration_seconds: float = 0.0
    estimated_cost_usd: float = 0.0
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = field(default_factory=dict)

    def get_task(self, task_id: str) -> Optional[PlannedTask]:
        for t in self.tasks:
            if t.task_id == task_id:
                return t
        return None

    def add_task(self, task: PlannedTask) -> None:
        if self.get_task(task.task_id):
            raise ValueError(f"Task {task.task_id} already exists in plan")
        self.tasks.append(task)

    def get_dependencies_map(self) -> Dict[str, List[str]]:
        return {t.task_id: list(t.dependencies) for t in self.tasks}

    def get_topological_order(self) -> List[PlannedTask]:
        """Returns tasks ordered topologically according to their dependencies."""
        in_degree: Dict[str, int] = {t.task_id: 0 for t in self.tasks}
        adj: Dict[str, List[str]] = {t.task_id: [] for t in self.tasks}

        for t in self.tasks:
            for dep in t.dependencies:
                if dep in adj:
                    adj[dep].append(t.task_id)
                    in_degree[t.task_id] += 1

        queue = [tid for tid, deg in in_degree.items() if deg == 0]
        order: List[str] = []

        while queue:
            curr = queue.pop(0)
            order.append(curr)
            for neighbor in adj[curr]:
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)

        if len(order) < len(self.tasks):
            raise ValueError("Cycle detected in execution plan dependencies")

        task_map = {t.task_id: t for t in self.tasks}
        return [task_map[tid] for tid in order]
