"""
Domain models for Enterprise Architecture Verification Framework Foundation (PART 2A).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
from typing import Any, Dict, List, Optional, Set, Tuple, Union


class RuleCategory(str, Enum):
    DEPENDENCY = "DEPENDENCY"
    BOUNDARY = "BOUNDARY"
    NAMING = "NAMING"
    COMPLEXITY = "COMPLEXITY"
    MODULARITY = "MODULARITY"


class RuleSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class RuleFailureAction(str, Enum):
    BLOCK_PIPELINE = "BLOCK_PIPELINE"
    REQUIRE_WAIVER = "REQUIRE_WAIVER"
    WARN_ONLY = "WARN_ONLY"


class ArchitectureCertificationBand(str, Enum):
    ENTERPRISE_ARCHITECTURE_READY = "ENTERPRISE_ARCHITECTURE_READY"  # 95-100
    PRODUCTION_ARCHITECTURE_READY = "PRODUCTION_ARCHITECTURE_READY"  # 90-94
    ACCEPTABLE = "ACCEPTABLE"                                        # 80-89
    NEEDS_IMPROVEMENT = "NEEDS_IMPROVEMENT"                          # 70-79
    FAILED = "FAILED"                                                # < 70


@dataclass
class ArchitectureRule:
    """Configurable architectural invariant rule."""
    id: str
    name: str
    category: RuleCategory
    severity: RuleSeverity
    description: str
    forbidden_import_patterns: List[Tuple[str, str]] = field(default_factory=list)  # (source_pattern, target_pattern)
    naming_forbidden_suffixes: List[Tuple[str, List[str]]] = field(default_factory=list)  # (module_pattern, suffixes)
    max_file_lines: int = 1000
    max_class_lines: int = 500
    max_function_lines: int = 100
    failure_action: RuleFailureAction = RuleFailureAction.BLOCK_PIPELINE


@dataclass
class ArchitectureDependency:
    """Directed dependency between two modules."""
    source_module: str
    target_module: str
    dependency_type: str = "import"  # "import" | "from_import" | "call"
    severity: RuleSeverity = RuleSeverity.LOW
    allowed: bool = True
    violation_rule_id: Optional[str] = None
    line_number: int = 0


@dataclass
class CircularDependencyCycle:
    """Detected circular dependency loop (A -> B -> C -> A)."""
    cycle_path: List[str]
    severity: RuleSeverity = RuleSeverity.CRITICAL
    description: str = ""


@dataclass
class ArchitectureViolation:
    """Specific architectural invariant violation found during scan."""
    violation_id: str
    rule_id: str
    rule_name: str
    category: RuleCategory
    severity: RuleSeverity
    source_file: str
    line_number: int
    message: str
    code_snippet: Optional[str] = None
    failure_action: RuleFailureAction = RuleFailureAction.BLOCK_PIPELINE


@dataclass
class ArchitectureDimensionScore:
    """Score for an individual architectural dimension."""
    dimension_name: str
    weight: float
    raw_score: float  # 0 to 100
    weighted_score: float  # raw_score * weight
    violations_count: int = 0


@dataclass
class ArchitectureScoreReport:
    """Consolidated architecture readiness scorecard."""
    total_score: float  # 0 to 100
    certification_band: ArchitectureCertificationBand
    dimension_scores: List[ArchitectureDimensionScore]
    total_violations_count: int
    critical_violations_count: int
    circular_dependencies_count: int
    is_deployable: bool


@dataclass
class ScanMetadata:
    """Metadata recording execution environment of architecture scan."""
    scan_id: str
    repository_root: str
    commit_sha: str
    scanner_version: str = "v2.0.0"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    total_files_scanned: int = 0
    total_lines_of_code: int = 0


@dataclass
class ArchitectureRegressionReport:
    """Comparison report between two scans detecting architectural regression."""
    baseline_scan_id: str
    current_scan_id: str
    score_delta: float
    new_violations: List[ArchitectureViolation]
    resolved_violations_count: int
    new_dependencies_count: int
    is_regression: bool
    blocking_reason: Optional[str] = None


@dataclass
class ArchitectureEvidencePackage:
    """Complete bundle of evidence generated by an architecture scan."""
    scan_id: str
    metadata: ScanMetadata
    dependency_graph: Dict[str, List[Dict[str, Any]]]
    violations: List[ArchitectureViolation]
    circular_cycles: List[CircularDependencyCycle]
    score_report: ArchitectureScoreReport
    evidence_sha256: str = ""

    def compute_sha256(self) -> str:
        payload = f"{self.scan_id}:{self.metadata.timestamp}:{self.score_report.total_score}:{len(self.violations)}:{len(self.circular_cycles)}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()
