"""
Multi-Region Failover Domain Subsystem.
"""
from app.platform_verification.multi_region_failover.domain.models import (
    CloudRegion,
    FailoverMode,
    ReplicationHealth,
    AvailabilityTier,
    RegionalServiceItem,
    MultiRegionArchitectureReport,
    CloudPortabilityReport,
    DatabaseReplicationReport,
    StorageReplicationReport,
    TrafficFailoverReport,
    WorkflowCheckpointReport,
    ChaosOutageReport,
    AvailabilityMetricsReport,
    MultiRegionScorecard,
)
from app.platform_verification.multi_region_failover.domain.interfaces import (
    IMultiRegionArchitectureValidator,
    ICloudPortabilityVerifier,
    IDatabaseReplicationVerifier,
    IStorageReplicationVerifier,
    ITrafficFailoverEngine,
    IWorkflowCheckpointVerifier,
    IChaosOutageSimulator,
    IAvailabilityMetricsEngine,
    IMultiRegionScoreEngine,
)

__all__ = [
    "CloudRegion",
    "FailoverMode",
    "ReplicationHealth",
    "AvailabilityTier",
    "RegionalServiceItem",
    "MultiRegionArchitectureReport",
    "CloudPortabilityReport",
    "DatabaseReplicationReport",
    "StorageReplicationReport",
    "TrafficFailoverReport",
    "WorkflowCheckpointReport",
    "ChaosOutageReport",
    "AvailabilityMetricsReport",
    "MultiRegionScorecard",
    "IMultiRegionArchitectureValidator",
    "ICloudPortabilityVerifier",
    "IDatabaseReplicationVerifier",
    "IStorageReplicationVerifier",
    "ITrafficFailoverEngine",
    "IWorkflowCheckpointVerifier",
    "IChaosOutageSimulator",
    "IAvailabilityMetricsEngine",
    "IMultiRegionScoreEngine",
]
