import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Network, Split } from 'lucide-react';
export const LiveDAGView = () => {
    const [selectedNodeId, setSelectedNodeId] = useState('node_merge_ocr');
    const [version, setVersion] = useState(1);
    const nodes = [
        { id: 'node_goal_ingress', name: 'Mission Goal Ingress', type: 'SEQUENTIAL', state: 'COMPLETED', worker: 'worker-planner-01', duration: '42ms', cost: '$0.0001' },
        { id: 'node_split_ocr', name: 'Split OCR Chunks', type: 'SPLIT', state: 'COMPLETED', worker: 'worker-dag-01', duration: '28ms', cost: '$0.0001' },
        { id: 'node_ocr_chunk_1', name: 'OCR Page 1-2 (Raster)', type: 'PARALLEL', state: 'COMPLETED', worker: 'worker-ocr-01', duration: '175ms', cost: '$0.0006' },
        { id: 'node_ocr_chunk_2', name: 'OCR Page 3-4 (Tables)', type: 'PARALLEL', state: 'COMPLETED', worker: 'worker-ocr-02', duration: '205ms', cost: '$0.0006' },
        { id: 'node_merge_ocr', name: 'Merge OCR Texts', type: 'MERGE', state: 'RUNNING', worker: 'worker-extract-01', duration: '60ms', cost: '$0.0002' },
        { id: 'node_extract_schema', name: 'Extract Financial Schema', type: 'SEQUENTIAL', state: 'WAITING', worker: 'worker-extract-01', duration: '140ms', cost: '$0.0008' },
        { id: 'node_validate_invariants', name: 'Scientific Validation Check', type: 'CONDITIONAL', state: 'WAITING', worker: 'worker-validate-01', duration: '90ms', cost: '$0.0003' },
        { id: 'node_barrier_governance', name: 'Governance Sync Barrier', type: 'BARRIER', state: 'WAITING', worker: 'worker-gov-01', duration: '50ms', cost: '$0.0002' },
        { id: 'node_join_finalize', name: 'Join & Truth Ledger Commit', type: 'JOIN', state: 'WAITING', worker: 'worker-trust-01', duration: '40ms', cost: '$0.0002' },
    ];
    const handleSimulateSplit = () => {
        setVersion(v => v + 1);
    };
    const selectedNode = nodes.find(n => n.id === selectedNodeId) ?? nodes[0];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 border border-blue-500/30 rounded-xl text-blue-400", children: _jsx(Network, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Live Dynamic DAG Topology & In-Flight Mutation", _jsxs(Badge, { variant: "success", size: "sm", children: ["Version v", version, ".0"] })] }), _jsx("p", { className: "text-xs text-[#94A3B8] font-mono", children: "Real-time directed acyclic graph driven by Phase 13.1 domain events (Split, Merge, Parallel, Barrier, Join)" })] })] }) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs(Button, { onClick: handleSimulateSplit, variant: "secondary", size: "sm", children: [_jsx(Split, { className: "w-3.5 h-3.5 mr-1 text-cyan-400" }), "Trigger Live Node Split Mutation"] }), _jsx(Badge, { variant: "intelligence", size: "md", children: "Critical Path: 425ms" })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "lg:col-span-2 space-y-3 font-mono", children: [_jsxs("div", { className: "text-xs font-semibold text-[#94A3B8] flex items-center justify-between", children: [_jsx("span", { children: "TOPOLOGICAL EXECUTION ORDER" }), _jsxs("span", { children: [nodes.length, " NODES TOTAL"] })] }), _jsx("div", { className: "space-y-2.5", children: nodes.map((node, idx) => {
                                    const isSelected = selectedNodeId === node.id;
                                    const isCompleted = node.state === 'COMPLETED';
                                    const isRunning = node.state === 'RUNNING';
                                    return (_jsxs(Card, { onClick: () => setSelectedNodeId(node.id), className: `p-3.5 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${isSelected
                                            ? 'border-cyan-500 bg-[#131D35] shadow-[0_0_12px_rgba(0,210,255,0.2)]'
                                            : isRunning
                                                ? 'border-indigo-500/60 bg-[#0F172A]'
                                                : isCompleted
                                                    ? 'border-emerald-500/30 bg-[#0F172A]/80'
                                                    : 'border-[#1E293B] bg-[#0A0F1D]/60 opacity-70'}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-xs text-[#64748B] w-6", children: [idx + 1, "."] }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-xs font-bold text-white", children: node.name }), _jsx(Badge, { variant: "default", size: "sm", children: node.type })] }), _jsxs("span", { className: "text-[10px] text-[#64748B]", children: ["Worker: ", node.worker] })] })] }), _jsxs("div", { className: "flex items-center gap-4 text-xs", children: [_jsx("span", { className: "text-[#94A3B8]", children: node.duration }), _jsx(Badge, { variant: isRunning ? 'intelligence' : isCompleted ? 'success' : 'outline', size: "sm", children: node.state })] })] }, node.id));
                                }) })] }), _jsx("div", { className: "space-y-4 font-mono", children: _jsxs(Card, { className: "p-5 rounded-2xl border border-[#1E293B] bg-[#0F172A] space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-[#1E293B] pb-3", children: [_jsxs("h3", { className: "text-xs font-bold text-white", children: ["Node Inspector: ", selectedNode.id] }), _jsx(Badge, { variant: "info", size: "sm", children: selectedNode.type })] }), _jsxs("div", { className: "space-y-3 text-xs", children: [_jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "TASK NAME" }), _jsx("span", { className: "text-white font-bold", children: selectedNode.name })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2", children: [_jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "STATUS" }), _jsx("span", { className: "text-cyan-400 font-bold", children: selectedNode.state })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "ASSIGNED WORKER" }), _jsx("span", { className: "text-purple-400 font-bold", children: selectedNode.worker })] })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "CRYPTOGRAPHIC TRUTH PROOF" }), _jsxs("span", { className: "text-emerald-400 font-bold text-[11px]", children: ["hash-dag-", selectedNode.id, "-verified"] })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "ESTIMATED LATENCY & COST" }), _jsxs("span", { className: "text-white font-bold", children: [selectedNode.duration, " \u2022 ", selectedNode.cost] })] })] })] }) })] })] }));
};
