import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { GitBranch, ShieldCheck } from 'lucide-react';
export const PlannerLifecycleView = () => {
    const [selectedState, setSelectedState] = useState('EXECUTING');
    const lifecycleStages = [
        { state: 'CREATED', phase: 'INITIAL', status: 'COMPLETED', time: '14:20:00.120', desc: 'Planner instance instantiated with correlation token.' },
        { state: 'INITIALIZING', phase: 'INITIAL', status: 'COMPLETED', time: '14:20:00.180', desc: 'Loaded runtime configurations and execution quotas.' },
        { state: 'CONTEXT_LOADING', phase: 'CONTEXT', status: 'COMPLETED', time: '14:20:00.220', desc: 'Fetched mission prompt and attached PDF document handles.' },
        { state: 'MEMORY_SEARCH', phase: 'CONTEXT', status: 'COMPLETED', time: '14:20:00.280', desc: 'Retrieved 3 historical invoice DAG templates from memory graph.' },
        { state: 'CAPABILITY_DISCOVERY', phase: 'DISCOVERY', status: 'COMPLETED', time: '14:20:00.310', desc: 'Discovered 6 active worker types (OCR, Schema, Validator, Ledger).' },
        { state: 'GOAL_ANALYSIS', phase: 'REASONING', status: 'COMPLETED', time: '14:20:00.350', desc: 'Extracted SLA constraint (30s) and financial arithmetic invariant.' },
        { state: 'PLAN_SYNTHESIS', phase: 'REASONING', status: 'COMPLETED', time: '14:20:00.420', desc: 'Generated multi-stage topology with parallel raster chunks.' },
        { state: 'TASK_DECOMPOSITION', phase: 'DAG_BUILD', status: 'COMPLETED', time: '14:20:00.510', desc: 'Decomposed goal into 9 typed execution task nodes.' },
        { state: 'DEPENDENCY_ANALYSIS', phase: 'DAG_BUILD', status: 'COMPLETED', time: '14:20:00.600', desc: 'Computed critical path (425ms) and topological dependencies.' },
        { state: 'WORKER_ASSIGNMENT', phase: 'DISPATCH', status: 'COMPLETED', time: '14:20:00.720', desc: 'Matched tasks to optimal worker capabilities.' },
        { state: 'READY', phase: 'DISPATCH', status: 'COMPLETED', time: '14:20:00.890', desc: 'Execution DAG validated and locked into runtime state.' },
        { state: 'EXECUTING', phase: 'RUNTIME', status: 'ACTIVE', time: '14:20:01.100', desc: 'Wavefront 1 & 2 dispatched and running across worker pool.' },
        { state: 'REPLANNING', phase: 'RESILIENCE', status: 'STANDBY', time: '---', desc: 'Autonomous recovery trigger ready upon invariant or failure signal.' },
        { state: 'COMPLETED', phase: 'FINAL', status: 'PENDING', time: '---', desc: 'Mission objective satisfied and truth ledger committed.' },
        { state: 'FAILED', phase: 'FINAL', status: 'STANDBY', time: '---', desc: 'Terminal failure containment circuit.' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-indigo-500/20 to-blue-500/20 border border-indigo-500/30 rounded-xl text-indigo-400", children: _jsx(GitBranch, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Autonomous Planner 14-State Lifecycle Engine", _jsx(Badge, { variant: "success", size: "sm", children: "Phase 13.2 Live" })] }), _jsx("p", { className: "text-xs text-[#94A3B8] font-mono", children: "Observable state machine driven exclusively by immutable Phase 13.1 domain events" })] })] }) }), _jsxs("div", { className: "flex items-center gap-2 font-mono text-xs", children: [_jsx("span", { className: "text-[#94A3B8]", children: "Active State:" }), _jsx(Badge, { variant: "intelligence", size: "md", children: "EXECUTING (Wavefront 2)" })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-3", children: lifecycleStages.map((stage, idx) => {
                    const isSelected = selectedState === stage.state;
                    const isCompleted = stage.status === 'COMPLETED';
                    const isActive = stage.status === 'ACTIVE';
                    return (_jsxs(Card, { className: `p-3.5 rounded-xl border transition-all cursor-pointer ${isSelected
                            ? 'border-indigo-500 bg-[#131D35] shadow-[0_0_15px_rgba(99,102,241,0.25)]'
                            : isActive
                                ? 'border-cyan-500/50 bg-[#0F172A]'
                                : isCompleted
                                    ? 'border-emerald-500/30 bg-[#0F172A]/70'
                                    : 'border-[#1E293B] bg-[#0A0F1D]/50 opacity-60'}`, onClick: () => setSelectedState(stage.state), children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("span", { className: "text-[10px] font-mono text-[#64748B]", children: ["STEP ", idx + 1] }), _jsx(Badge, { variant: isActive ? 'intelligence' : isCompleted ? 'success' : 'outline', size: "sm", children: stage.status })] }), _jsx("div", { className: "text-xs font-mono font-bold text-white mb-1", children: stage.state }), _jsx("div", { className: "text-[11px] text-[#94A3B8] line-clamp-2 mb-2", children: stage.desc }), _jsxs("div", { className: "text-[10px] font-mono text-[#64748B] flex items-center justify-between pt-2 border-t border-[#1E293B]", children: [_jsx("span", { children: stage.phase }), _jsx("span", { children: stage.time })] })] }, stage.state));
                }) }), _jsxs(Card, { className: "p-5 rounded-2xl border border-[#1E293B] bg-[#0F172A] space-y-4 font-mono", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-[#1E293B] pb-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(ShieldCheck, { className: "w-4 h-4 text-cyan-400" }), _jsxs("h3", { className: "text-sm font-semibold text-white", children: ["State Detail & Cryptographic Provenance: ", selectedState] })] }), _jsx(Badge, { variant: "info", size: "sm", children: "Deterministic Runtime Event" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4 text-xs", children: [_jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[#64748B] block text-[10px]", children: "CORRESPONDING EVENT TYPE" }), _jsx("span", { className: "text-white font-bold", children: "PlannerStateChanged" })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[#64748B] block text-[10px]", children: "EVENT ID" }), _jsxs("span", { className: "text-cyan-400 font-bold", children: ["evt-state-", selectedState.toLowerCase(), "-01"] })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[#64748B] block text-[10px]", children: "TRUTH LEDGER COMMIT" }), _jsx("span", { className: "text-emerald-400 font-bold", children: "hash-state-verified-c8a1" })] }), _jsxs("div", { className: "p-3 bg-[#131D35] rounded-xl border border-[#1E293B]", children: [_jsx("span", { className: "text-[#64748B] block text-[10px]", children: "REPLAY STREAM OFFSET" }), _jsx("span", { className: "text-purple-400 font-bold", children: "Offset #04" })] })] })] })] }));
};
