import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { Cpu } from 'lucide-react';
export const SchedulerView = () => {
    const workers = [
        { id: 'worker-ocr-01', role: 'OCR_EXTRACTION', status: 'BUSY', cpu: 28.5, mem: '256 MB', activeTask: 'node_ocr_chunk_1', completed: 18 },
        { id: 'worker-ocr-02', role: 'OCR_EXTRACTION', status: 'BUSY', cpu: 34.0, mem: '256 MB', activeTask: 'node_ocr_chunk_2', completed: 14 },
        { id: 'worker-extract-01', role: 'SCHEMA_EXTRACTION', status: 'RUNNING', cpu: 18.0, mem: '512 MB', activeTask: 'node_merge_ocr', completed: 22 },
        { id: 'worker-validate-01', role: 'SCIENTIFIC_VALIDATION', status: 'IDLE', cpu: 5.0, mem: '128 MB', activeTask: 'None', completed: 20 },
        { id: 'worker-gov-01', role: 'GOVERNANCE_AUDIT', status: 'IDLE', cpu: 3.0, mem: '128 MB', activeTask: 'None', completed: 8 },
        { id: 'worker-trust-01', role: 'TRUTH_LEDGER_COMMIT', status: 'IDLE', cpu: 4.0, mem: '256 MB', activeTask: 'None', completed: 12 },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/30 rounded-xl text-emerald-400", children: _jsx(Cpu, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Runtime DAG Scheduler & Concurrency Wavefronts", _jsx(Badge, { variant: "success", size: "sm", children: "6 Workers Online" })] }), _jsx("p", { className: "text-xs text-[#94A3B8] font-mono", children: "Load balancing, queue latencies, and capability matching heuristics" })] })] }) }), _jsxs("div", { className: "flex items-center gap-3 font-mono text-xs", children: [_jsx(Badge, { variant: "intelligence", size: "md", children: "Concurrency Limit: 8" }), _jsx(Badge, { variant: "outline", size: "md", children: "Avg Queue: 14.5ms" })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 font-mono", children: workers.map(w => (_jsxs(Card, { className: "p-4 rounded-xl border border-[#1E293B] bg-[#0F172A] space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-xs font-bold text-white", children: w.id }), _jsx(Badge, { variant: w.status === 'BUSY' ? 'warning' : w.status === 'RUNNING' ? 'intelligence' : 'success', size: "sm", children: w.status })] }), _jsxs("div", { className: "text-[11px] text-[#94A3B8]", children: ["Role: ", _jsx("span", { className: "text-white font-semibold", children: w.role })] }), _jsxs("div", { className: "p-2.5 bg-[#131D35] rounded-lg border border-[#1E293B] space-y-1 text-xs", children: [_jsxs("div", { className: "flex justify-between text-[#64748B]", children: [_jsx("span", { children: "Active Task:" }), _jsx("span", { className: "text-cyan-400 font-bold", children: w.activeTask })] }), _jsxs("div", { className: "flex justify-between text-[#64748B]", children: [_jsx("span", { children: "CPU / Mem:" }), _jsxs("span", { className: "text-white", children: [w.cpu, "% \u2022 ", w.mem] })] })] }), _jsxs("div", { className: "flex justify-between items-center text-[10px] text-[#64748B] pt-2 border-t border-[#1E293B]", children: [_jsxs("span", { children: ["Tasks Completed: ", w.completed] }), _jsx("span", { className: "text-emerald-400 font-semibold", children: "Healthy" })] })] }, w.id))) })] }));
};
