import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
export const ExtensionLifecycleView = () => {
    const lifecycleActions = [
        { action: 'UPGRADE', pluginId: 'plugin.invoice.processing', details: 'Upgraded v1.3.2 -> v1.4.0 (Mod11 speedup)', time: '18:10:04 UTC', status: 'SUCCESS' },
        { action: 'ENABLE', pluginId: 'plugin.medical.records', details: 'Activated HIPAA de-identification sandbox', time: '18:12:20 UTC', status: 'SUCCESS' },
        { action: 'HOT_RELOAD', pluginId: 'plugin.resume.screener', details: 'Dynamic AST re-compiled in 14ms', time: '18:15:30 UTC', status: 'SUCCESS' },
        { action: 'LOCK_VERSION', pluginId: 'plugin.legal.contracts', details: 'Pinned to v1.1.5 (SHA-256 attested)', time: '18:18:10 UTC', status: 'SUCCESS' },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-border/40 pb-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Extension Lifecycle & Versioning" }), _jsx(Badge, { variant: "success", size: "sm", children: "Hot-Reload & Rollback Safe" })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-1", children: "Zero-downtime hot reloading, automated rollback history, SemVer dependency locking, and dynamic lifecycle events." })] }), _jsx(Badge, { variant: "outline", size: "md", children: "Zero Restart Required" })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "text-xs font-semibold uppercase tracking-wider text-muted-foreground", children: ["Recent Lifecycle Operations (", lifecycleActions.length, ")"] }), lifecycleActions.map((item, idx) => (_jsxs(Card, { className: "p-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: item.action }), _jsxs("div", { children: [_jsx("div", { className: "font-mono text-xs font-bold text-foreground", children: item.pluginId }), _jsx("div", { className: "text-xs text-muted-foreground mt-0.5", children: item.details })] })] }), _jsxs("div", { className: "text-right font-mono", children: [_jsx("span", { className: "text-xs text-muted-foreground", children: item.time }), _jsxs("div", { className: "text-emerald-400 text-xs font-bold mt-0.5", children: ["\u2713 ", item.status] })] })] }, idx)))] })] }));
};
