import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { TrendingUp, Target } from 'lucide-react';
export const ConfidenceEvolutionViewer = () => {
    const steps = [
        { frame: 0, score: 50.0, unc: 20.0, formula: 'Prior Init', trigger: 'mission.started' },
        { frame: 2, score: 75.0, unc: 12.0, formula: 'WeightedEnsemble (v1.3.0)', trigger: 'planner.dag' },
        { frame: 5, score: 94.2, unc: 4.5, formula: 'WeightedEnsemble (v1.3.0)', trigger: 'worker.completed' },
        { frame: 8, score: 98.42, unc: 1.45, formula: 'WeightedEnsemble (v1.3.0)', trigger: 'truth.merkle' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-purple-500/20 to-pink-500/20 border border-purple-500/30 rounded-xl text-purple-400", children: _jsx(TrendingUp, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Confidence Evolution Viewer", _jsx(Badge, { variant: "intelligence", size: "sm", children: "Scientific Lineage Replay" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Frame-by-frame confidence score, uncertainty intervals, and formula version progression." })] })] }) }), _jsx("div", { className: "flex items-center gap-3", children: _jsx(Badge, { variant: "success", size: "sm", children: "Converged: 98.42%" }) })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4 font-mono", children: steps.map((s) => (_jsxs(Card, { className: "p-4 bg-[#0F172A] border-[#1E293B] space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between text-xs text-slate-400", children: [_jsxs("span", { children: ["Frame #", s.frame] }), _jsx(Badge, { variant: "outline", size: "sm", children: s.trigger })] }), _jsxs("div", { className: "text-2xl font-bold text-white mt-1", children: [s.score.toFixed(2), "%"] }), _jsxs("div", { className: "text-[11px] text-slate-400", children: ["Uncertainty: \u00B1", s.unc.toFixed(2), "%"] }), _jsx("div", { className: "text-[10px] text-cyan-400 truncate pt-2 border-t border-slate-800", children: s.formula })] }, s.frame))) }), _jsxs(Card, { className: "p-5 bg-[#0F172A] border-[#1E293B] font-mono text-xs space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-800 pb-2", children: [_jsxs("span", { className: "font-bold text-slate-200 flex items-center gap-2", children: [_jsx(Target, { className: "w-4 h-4 text-cyan-400" }), "Calibration & Invariance Confirmation"] }), _jsx(Badge, { variant: "success", size: "sm", children: "Monotonic Bounds Maintained" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 text-slate-300", children: [_jsxs("div", { children: ["Expected Calibration Error: ", _jsx("span", { className: "text-emerald-400 font-bold", children: "0.014 (Optimal)" })] }), _jsxs("div", { children: ["Brier Score: ", _jsx("span", { className: "text-cyan-400 font-bold", children: "0.018" })] }), _jsxs("div", { children: ["Cryptographic Seal: ", _jsx("span", { className: "text-amber-400 font-bold", children: "sha256:7fa189c4..." })] })] })] })] }));
};
