import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export const EvidenceExplorerView = ({ missionId }) => {
    const [selectedTab, setSelectedTab] = useState('SMT_INVARIANTS');
    return (_jsxs("div", { className: "bg-slate-950 border border-slate-800 rounded-xl p-6 shadow-2xl space-y-6 text-slate-100", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-4", children: [_jsxs("div", { children: [_jsxs("h3", { className: "text-lg font-bold text-white flex items-center gap-2", children: [_jsx("span", { children: "\uD83D\uDD2C" }), " Forensic Evidence & Invariant Proof Explorer"] }), _jsx("p", { className: "text-xs text-slate-400 mt-1", children: "Reconstruct visual bounding boxes, OCR spatial tokens, and formal SMT arithmetic invariants at this replay step." })] }), _jsxs("div", { className: "flex bg-slate-900 border border-slate-800 p-1 rounded-lg", children: [_jsx("button", { onClick: () => setSelectedTab('SMT_INVARIANTS'), className: `px-3 py-1 text-xs font-mono rounded ${selectedTab === 'SMT_INVARIANTS' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'}`, children: "SMT Invariants" }), _jsx("button", { onClick: () => setSelectedTab('OCR_BOXES'), className: `px-3 py-1 text-xs font-mono rounded ${selectedTab === 'OCR_BOXES' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'}`, children: "Spatial BBoxes" }), _jsx("button", { onClick: () => setSelectedTab('SOURCE_CROPS'), className: `px-3 py-1 text-xs font-mono rounded ${selectedTab === 'SOURCE_CROPS' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'}`, children: "Artifact Inspection" })] })] }), selectedTab === 'SMT_INVARIANTS' && (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-emerald-950/40 border border-emerald-500/40 p-4 rounded-xl", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-xs font-mono font-bold text-emerald-400", children: "SMT FORMAL PROOF: SATISFIABLE (SAT)" }), _jsx("span", { className: "text-xs font-mono text-slate-300", children: "Z3 / CVC5 Proof Engine" })] }), _jsx("p", { className: "text-xs text-emerald-200 mt-1", children: "Arithmetic Invariant Verified: Total = Subtotal ($4,250.00) + Tax ($340.00) - Discount ($0.00) == $4,590.00." })] }), _jsxs("div", { className: "bg-slate-900 p-4 rounded-xl border border-slate-800 space-y-2", children: [_jsx("span", { className: "text-xs font-bold text-slate-400 font-mono", children: "Formal Assertion Script" }), _jsx("pre", { className: "text-xs text-cyan-300 font-mono bg-slate-950 p-3 rounded overflow-x-auto", children: `(declare-const subtotal Real)
(declare-const tax Real)
(declare-const total Real)
(assert (= subtotal 4250.00))
(assert (= tax 340.00))
(assert (= total (+ subtotal tax)))
(check-sat)
(get-model)` })] })] })), selectedTab === 'OCR_BOXES' && (_jsxs("div", { className: "bg-slate-900 border border-slate-800 p-6 rounded-xl text-center space-y-3", children: [_jsx("span", { className: "text-slate-400 text-xs font-mono", children: "Extracted 28 layout tokens with sub-pixel normalized coordinate bounding boxes [ymin, xmin, ymax, xmax]." }), _jsx("div", { className: "h-48 bg-slate-950 border border-slate-800 rounded-lg flex items-center justify-center text-slate-500 text-xs font-mono", children: "[ Spatial Coordinate Overlay Rendered Deterministically from Event Stream ]" })] })), selectedTab === 'SOURCE_CROPS' && (_jsxs("div", { className: "bg-slate-900 border border-slate-800 p-6 rounded-xl text-center text-slate-400 text-xs font-mono", children: ["Artifacts for Mission ", missionId, ": Raw PDF, Clean OCR Vector Layer, Extracted JSON Schema."] }))] }));
};
