import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useWorkspace } from '../context/WorkspaceContext';
import { CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
export const MissionReplayPlayer = () => {
    const { replaySnapshots, currentReplayStep, isReplaying, setReplayStep, playReplay, pauseReplay, stepForwardReplay, stepBackwardReplay, } = useWorkspace();
    const activeSnapshot = replaySnapshots[currentReplayStep - 1] || replaySnapshots[0] || null;
    return (_jsxs("div", { className: "w-full flex flex-col h-[700px] rounded-2xl bg-[#0F172A]/90 border border-[#1E293B] shadow-2xl overflow-hidden", children: [_jsxs(CardHeader, { className: "flex flex-row items-center justify-between py-4 px-6 border-b border-[#1E293B] bg-[#131D35]/50", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "sm", hasDot: true, isPulsing: isReplaying, children: "TIME MACHINE REPLAY" }), _jsxs("span", { className: "text-xs text-[#94A3B8] font-mono", children: ["Step ", currentReplayStep, " of ", replaySnapshots.length] })] }), _jsx(CardTitle, { className: "mt-1 text-base font-bold text-[#F8FAFC]", children: "Deterministic Mission Replay & Execution Scrubber" })] }), _jsx("div", { className: "flex items-center gap-2", children: isReplaying ? (_jsx(Button, { variant: "secondary", size: "sm", onClick: pauseReplay, children: "\u23F8 Pause Playback" })) : (_jsx(Button, { variant: "intelligence", size: "sm", onClick: playReplay, children: "\u25B6 Auto Play" })) })] }), _jsxs(CardContent, { className: "flex-1 overflow-y-auto p-6 space-y-6 flex flex-col justify-between", children: [activeSnapshot && (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "p-4 rounded-xl bg-[#131D35] border border-[#1E293B] space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between text-xs font-mono", children: [_jsxs("span", { className: "text-[#00D2FF]", children: ["Current Checkpoint: [", activeSnapshot.timestampUtc, " UTC]"] }), _jsxs("span", { className: "text-[#10B981] font-bold", children: ["Stage: ", activeSnapshot.stageName, " (", activeSnapshot.activeAgent, ")"] })] }), _jsx("input", { type: "range", min: 1, max: replaySnapshots.length, value: currentReplayStep, onChange: (e) => setReplayStep(Number(e.target.value)), className: "w-full accent-cyan-400 cursor-pointer" }), _jsxs("div", { className: "flex items-center justify-between pt-2", children: [_jsx(Button, { variant: "ghost", size: "sm", onClick: stepBackwardReplay, disabled: currentReplayStep <= 1, children: "\u23EE Step Backward" }), _jsx("div", { className: "flex gap-2", children: replaySnapshots.map((s, idx) => (_jsx("button", { onClick: () => setReplayStep(idx + 1), className: `h-6 w-6 rounded-full text-[10px] font-mono font-bold transition-all ${currentReplayStep === idx + 1
                                                        ? 'bg-[#00D2FF] text-slate-900 shadow-[0_0_10px_rgba(0,210,255,0.8)]'
                                                        : 'bg-[#0A0F1D] text-[#64748B] hover:text-[#F8FAFC]'}`, children: idx + 1 }, s.stepIndex))) }), _jsx(Button, { variant: "ghost", size: "sm", onClick: stepForwardReplay, disabled: currentReplayStep >= replaySnapshots.length, children: "Step Forward \u23ED" })] })] }), _jsxs("div", { className: "p-6 rounded-2xl bg-[#131D35] border border-cyan-500/30 shadow-lg space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-[#1E293B] pb-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "md", children: activeSnapshot.activeAgent }), _jsx("h3", { className: "text-sm font-bold text-[#F8FAFC]", children: activeSnapshot.thoughtTitle })] }), _jsxs("span", { className: "text-xs font-mono text-[#00D2FF] font-bold", children: ["Confidence: ", (activeSnapshot.currentConfidence * 100).toFixed(1), "%"] })] }), _jsxs("div", { className: "space-y-2 text-xs", children: [_jsx("span", { className: "text-[10px] font-mono uppercase text-[#64748B] block", children: "Cognitive Reasoning at this moment:" }), _jsxs("p", { className: "p-3 rounded-lg bg-[#0A0F1D] border border-[#1E293B] text-[#F8FAFC] font-mono leading-relaxed", children: ["\"", activeSnapshot.thoughtContent, "\""] })] }), activeSnapshot.activeDecisionTitle && (_jsxs("div", { className: "pt-2 flex items-center justify-between text-xs font-mono text-[#10B981]", children: [_jsxs("span", { children: ["\u26A1 Active Decision: ", activeSnapshot.activeDecisionTitle] }), _jsxs("span", { children: ["Tasks Done: ", activeSnapshot.completedTasksCount] })] })), activeSnapshot.memoryAccessTitle && (_jsxs("div", { className: "pt-1 text-[11px] font-mono text-[#A855F7] flex items-center gap-1.5", children: [_jsx("span", { children: "\uD83E\uDDE0 Memory Retrieved:" }), _jsx("span", { children: activeSnapshot.memoryAccessTitle })] }))] })] })), _jsx("div", { className: "p-3 rounded-xl bg-[#0A0F1D] border border-[#1E293B] text-center text-xs font-mono text-[#64748B]", children: "Deterministic Provenance: Replay matches underlying SHA-256 state ledger 1:1." })] })] }));
};
