import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { Compass, RotateCcw } from 'lucide-react';
export const MissionTimeTravelExplorer = () => {
    const checkpoints = [
        { id: 'chk_00', cursor: 0, label: 'Prior Ingestion Baseline', hash: 'sha256:0018fa...', size: '1.2 KB' },
        { id: 'chk_04', cursor: 4, label: 'OCR Step Completion Checkpoint', hash: 'sha256:7fa189...', size: '3.4 KB' },
        { id: 'chk_08', cursor: 8, label: 'Final Truth Ledger Sealing', hash: 'sha256:99cba1...', size: '4.8 KB' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-indigo-500/20 to-teal-500/20 border border-indigo-500/30 rounded-xl text-indigo-400", children: _jsx(Compass, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Mission Time Travel & Checkpoint Explorer", _jsx(Badge, { variant: "intelligence", size: "sm", children: "Instant Point-in-Time Restore" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Jump to historical execution checkpoints, restore state snapshots, and inspect point-in-time runtime graphs." })] })] }) }), _jsx("div", { className: "flex items-center gap-3", children: _jsx(Badge, { variant: "outline", size: "sm", children: "3 Checkpoints Indexed" }) })] }), _jsx("div", { className: "space-y-4 font-mono text-xs", children: checkpoints.map((cp) => (_jsxs(Card, { className: "p-5 bg-[#0F172A] border-[#1E293B] hover:border-indigo-500/40 transition-all flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-indigo-400 font-bold", children: ["#", cp.cursor] }), _jsx("span", { className: "text-white font-bold text-sm", children: cp.label }), _jsx(Badge, { variant: "outline", size: "sm", children: cp.id })] }), _jsxs("div", { className: "text-slate-400 text-[11px] flex items-center gap-3 mt-1", children: [_jsxs("span", { children: ["State Hash: ", _jsx("code", { className: "text-slate-300 bg-slate-900 px-1 py-0.5 rounded", children: cp.hash })] }), _jsxs("span", { children: ["Size: ", _jsx("span", { className: "text-slate-300", children: cp.size })] })] })] }), _jsxs("button", { className: "px-3 py-1.5 bg-indigo-500/20 hover:bg-indigo-500/30 text-indigo-300 border border-indigo-500/40 rounded-lg flex items-center gap-1.5 transition-colors text-xs font-semibold", children: [_jsx(RotateCcw, { className: "w-3.5 h-3.5" }), " Restore State at #", cp.cursor] })] }, cp.id))) })] }));
};
