import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { Network, CheckCircle2, ArrowRight } from 'lucide-react';
export const PlannerDAGReplay = () => {
    const dagNodes = [
        { id: 'node_ocr_01', name: 'OCR Text & Layout', worker: 'worker_gpu_ocr', status: 'COMPLETED', duration: '285ms' },
        { id: 'node_schema_01', name: 'Schema Matching & Field Extraction', worker: 'worker_schema_01', status: 'COMPLETED', duration: '190ms' },
        { id: 'node_smt_01', name: 'SMT Balance Verification', worker: 'worker_truth_01', status: 'COMPLETED', duration: '45ms' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-indigo-500/20 to-blue-500/20 border border-indigo-500/30 rounded-xl text-indigo-400", children: _jsx(Network, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Planner & DAG Replay Studio", _jsx(Badge, { variant: "intelligence", size: "sm", children: "Wavefront Sequencing" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Event-driven reconstruction of planner state transitions, DAG topology, and worker scheduling." })] })] }) }), _jsx("div", { className: "flex items-center gap-3", children: _jsx(Badge, { variant: "success", size: "sm", children: "Critical Path: 520ms" }) })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs", children: dagNodes.map((n, idx) => (_jsxs(Card, { className: "p-5 bg-[#0F172A] border-[#1E293B] space-y-3 relative hover:border-indigo-500/40 transition-all", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-800 pb-2", children: [_jsxs("span", { className: "font-bold text-cyan-400", children: ["Step #", idx + 1] }), _jsxs(Badge, { variant: "success", size: "sm", children: [_jsx(CheckCircle2, { className: "w-3 h-3 inline mr-1" }), n.status] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-bold text-white", children: n.name }), _jsxs("div", { className: "text-slate-400 text-[11px] mt-0.5", children: ["ID: ", n.id] })] }), _jsxs("div", { className: "p-2.5 bg-slate-900/60 rounded border border-slate-800 space-y-1 text-[11px]", children: [_jsxs("div", { className: "text-slate-400", children: ["Worker: ", _jsx("span", { className: "text-purple-300 font-bold", children: n.worker })] }), _jsxs("div", { className: "text-slate-400", children: ["Duration: ", _jsx("span", { className: "text-emerald-400 font-bold", children: n.duration })] })] }), idx < dagNodes.length - 1 && (_jsx("div", { className: "hidden md:flex absolute -right-3 top-1/2 -translate-y-1/2 z-10 w-6 h-6 rounded-full bg-slate-800 border border-slate-700 items-center justify-center text-slate-400", children: _jsx(ArrowRight, { className: "w-3 h-3" }) }))] }, n.id))) })] }));
};
