import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { ShieldCheck, CheckCircle2 } from 'lucide-react';
export const ReplayVerificationCenter = () => {
    const verifications = [
        { check: 'Event Hash Chain Continuity', result: 'VALID', details: '10/10 parent-child SHA256 hashes matched without gaps' },
        { check: 'Truth Ledger Invariant Seal', result: 'VALID', details: 'Merkle root sha256:7fa189c4... confirmed in Truth Ledger' },
        { check: 'Formula Monotonic Bounds [0, 1]', result: 'VALID', details: 'WeightedEnsemble (v1.3.0) confirmed monotonically bounded' },
        { check: 'Projection Monotonic Sequencing', result: 'VALID', details: 'Zero out-of-order or duplicate events encountered' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/30 rounded-xl text-emerald-400", children: _jsx(ShieldCheck, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Replay Verification & Authenticity Center", _jsx(Badge, { variant: "success", size: "sm", children: "100% Verified" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Independent cryptographic proof validation guaranteeing zero UI fabrication and absolute replay integrity." })] })] }) }), _jsx("div", { className: "flex items-center gap-3", children: _jsx(Badge, { variant: "intelligence", size: "sm", children: "Verification Hash: sha256:7fa189c4..." }) })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs", children: verifications.map((v, idx) => (_jsxs(Card, { className: "p-5 bg-[#0F172A] border-[#1E293B] space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-bold text-white text-sm", children: v.check }), _jsxs(Badge, { variant: "success", size: "sm", className: "flex items-center gap-1", children: [_jsx(CheckCircle2, { className: "w-3 h-3" }), v.result] })] }), _jsx("p", { className: "text-slate-400 text-xs", children: v.details })] }, idx))) })] }));
};
