import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { Clock, Search, Layers, CheckCircle2, ChevronRight, Hash } from 'lucide-react';
const mockTimelineEvents = [
    { id: 'evt_001', cursor: 0, type: 'mission.started', subsystem: 'mission', timestamp: '00:00:01', summary: 'Mission Ingestion initialized', payloadJson: '{"goal": "Process multi-page enterprise invoice"}' },
    { id: 'evt_002', cursor: 1, type: 'planner.lifecycle.transition', subsystem: 'planner', timestamp: '00:00:02', summary: 'Planner entered GOAL_ANALYSIS state', payloadJson: '{"state": "GOAL_ANALYSIS"}' },
    { id: 'evt_003', cursor: 2, type: 'planner.task_decomposed', subsystem: 'planner', timestamp: '00:00:03', summary: 'Decomposed into OCR, Schema, and SMT tasks', payloadJson: '{"tasks_count": 3}' },
    { id: 'evt_004', cursor: 3, type: 'schedule.assigned', subsystem: 'scheduler', timestamp: '00:00:04', summary: 'Task task_ocr_01 allocated to worker_gpu_01', payloadJson: '{"worker_id": "worker_gpu_01"}' },
    { id: 'evt_005', cursor: 4, type: 'worker.started', subsystem: 'worker', timestamp: '00:00:05', summary: 'Worker worker_gpu_01 started OCR pipeline', payloadJson: '{"role": "ocr_specialist"}' },
    { id: 'evt_006', cursor: 5, type: 'worker.completed', subsystem: 'worker', timestamp: '00:00:08', summary: 'OCR step finished in 285ms (confidence 0.96)', payloadJson: '{"duration_ms": 285.0}' },
    { id: 'evt_007', cursor: 6, type: 'confidence.evaluated', subsystem: 'confidence', timestamp: '00:00:09', summary: 'Confidence evaluated via WeightedEnsemble (v1.3.0)', payloadJson: '{"overall_score": 0.942}' },
    { id: 'evt_008', cursor: 7, type: 'truth.invariant.checked', subsystem: 'truth', timestamp: '00:00:12', summary: 'SMT total balance proof satisfied: Subtotal + Tax == Total', payloadJson: '{"passed": true}' },
    { id: 'evt_009', cursor: 8, type: 'truth.merkle_root.sealed', subsystem: 'truth', timestamp: '00:00:13', summary: 'Sealed Merkle root into immutable truth chain', payloadJson: '{"merkle_root": "sha256:7fa189c4..."}' },
    { id: 'evt_010', cursor: 9, type: 'mission.completed', subsystem: 'mission', timestamp: '00:00:15', summary: 'Mission finished successfully with 100% truth proofs', payloadJson: '{"final_confidence": 0.9842}' },
];
export const ReplayTimelineExplorer = () => {
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedSubsystem, setSelectedSubsystem] = useState('ALL');
    const [selectedEvent, setSelectedEvent] = useState(mockTimelineEvents[0] || null);
    const filtered = mockTimelineEvents.filter((ev) => {
        const matchesSearch = ev.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
            ev.type.toLowerCase().includes(searchTerm.toLowerCase()) ||
            ev.summary.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesSub = selectedSubsystem === 'ALL' || ev.subsystem === selectedSubsystem;
        return matchesSearch && matchesSub;
    });
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-500/30 rounded-xl text-indigo-400", children: _jsx(Clock, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Replay Timeline Explorer", _jsx(Badge, { variant: "intelligence", size: "sm", children: "Immutable Chronology" })] }), _jsx("p", { className: "text-xs text-slate-400", children: "Inspect raw domain event streams with cryptographic payload verification and subsystem categorization." })] })] }) }), _jsx("div", { className: "flex items-center gap-3", children: _jsxs(Badge, { variant: "success", size: "sm", children: [filtered.length, " Events Listed"] }) })] }), _jsxs("div", { className: "flex flex-wrap items-center gap-4 bg-[#0F172A] p-4 rounded-xl border border-[#1E293B]", children: [_jsxs("div", { className: "relative flex-1 min-w-[240px]", children: [_jsx(Search, { className: "w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" }), _jsx("input", { type: "text", placeholder: "Search events by ID, type, summary...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full pl-9 pr-4 py-2 bg-[#0B1120] border border-[#1E293B] rounded-lg text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500" })] }), _jsxs("select", { value: selectedSubsystem, onChange: (e) => setSelectedSubsystem(e.target.value), className: "bg-[#0B1120] border border-[#1E293B] rounded-lg px-3 py-2 text-sm text-slate-200 focus:outline-none focus:border-indigo-500", children: [_jsx("option", { value: "ALL", children: "All Subsystems" }), _jsx("option", { value: "mission", children: "Mission" }), _jsx("option", { value: "planner", children: "Planner" }), _jsx("option", { value: "scheduler", children: "Scheduler" }), _jsx("option", { value: "worker", children: "Worker" }), _jsx("option", { value: "confidence", children: "Confidence" }), _jsx("option", { value: "truth", children: "Truth" })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsx(Card, { className: "lg:col-span-2 p-4 bg-[#0F172A] border-[#1E293B] space-y-2 max-h-[600px] overflow-y-auto", children: filtered.map((ev) => {
                            const isSelected = selectedEvent?.id === ev.id;
                            return (_jsxs("div", { onClick: () => setSelectedEvent(ev), className: `p-3 rounded-lg border transition-all cursor-pointer flex items-center justify-between font-mono text-xs ${isSelected
                                    ? 'bg-indigo-500/10 border-indigo-500/50 text-white'
                                    : 'bg-slate-900/40 border-slate-800 text-slate-300 hover:bg-slate-800/60'}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "w-6 h-6 rounded bg-slate-800 flex items-center justify-center text-[10px] text-slate-400 font-bold", children: ["#", ev.cursor] }), _jsxs("div", { children: [_jsxs("div", { className: "font-bold text-slate-100 flex items-center gap-2", children: [_jsx("span", { children: ev.type }), _jsx(Badge, { variant: "outline", size: "sm", children: ev.subsystem })] }), _jsx("div", { className: "text-[11px] text-slate-400 mt-0.5", children: ev.summary })] })] }), _jsxs("div", { className: "flex items-center gap-2 text-slate-500 text-[11px]", children: [_jsx("span", { children: ev.timestamp }), _jsx(ChevronRight, { className: "w-3.5 h-3.5" })] })] }, ev.id));
                        }) }), _jsx(Card, { className: "p-5 bg-[#0F172A] border-[#1E293B] flex flex-col justify-between font-mono text-xs", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-800 pb-2", children: [_jsxs("span", { className: "font-bold text-slate-200 flex items-center gap-1.5", children: [_jsx(Hash, { className: "w-3.5 h-3.5 text-indigo-400" }), selectedEvent?.id] }), _jsxs(Badge, { variant: "success", size: "sm", children: [_jsx(CheckCircle2, { className: "w-3 h-3 inline mr-1" }), "Verified"] })] }), _jsxs("div", { className: "text-slate-400 space-y-1", children: [_jsxs("div", { children: ["Type: ", _jsx("span", { className: "text-indigo-300 font-bold", children: selectedEvent?.type })] }), _jsxs("div", { children: ["Subsystem: ", _jsx("span", { className: "text-slate-200 capitalize", children: selectedEvent?.subsystem })] }), _jsxs("div", { children: ["Timestamp: ", _jsx("span", { className: "text-slate-300", children: selectedEvent?.timestamp })] })] }), _jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "text-slate-400 font-semibold flex items-center gap-1", children: [_jsx(Layers, { className: "w-3.5 h-3.5" }), " Payload Details:"] }), _jsx("pre", { className: "p-3 bg-slate-950 rounded-lg border border-slate-800 text-[11px] text-cyan-300 overflow-x-auto", children: JSON.stringify(JSON.parse(selectedEvent?.payloadJson || '{}'), null, 2) })] })] }) })] })] }));
};
