import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { BarChart3 } from 'lucide-react';
export const FeatureContributionWaterfall = () => {
    const waterfallSteps = [
        { step: 1, feature: 'validation_constraint_satisfaction', value: 1.000, weight: '35%', contribution: '+0.3500', runningTotal: '35.0%' },
        { step: 2, feature: 'ocr_mean_confidence', value: 0.992, weight: '20%', contribution: '+0.1984', runningTotal: '54.8%' },
        { step: 3, feature: 'extraction_cross_field_consistency', value: 0.990, weight: '20%', contribution: '+0.1980', runningTotal: '74.6%' },
        { step: 4, feature: 'evidence_hash_integrity', value: 1.000, weight: '15%', contribution: '+0.1500', runningTotal: '89.6%' },
        { step: 5, feature: 'planner_dag_efficiency', value: 0.950, weight: '10%', contribution: '+0.0950', runningTotal: '99.1%' },
        { step: 6, feature: 'temperature_scaling_calibration', value: 1.050, weight: 'CALIB', contribution: '-0.0070', runningTotal: '98.4%' },
    ];
    return (_jsxs("div", { className: "p-6 space-y-6 bg-[#0B1120] min-h-screen text-[#F8FAFC]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4 border-b border-[#1E293B] pb-6", children: [_jsx("div", { className: "space-y-1", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-gradient-to-br from-cyan-500/20 to-teal-500/20 border border-cyan-500/30 rounded-xl text-cyan-400", children: _jsx(BarChart3, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsxs("h1", { className: "text-xl font-bold font-mono tracking-tight text-white flex items-center gap-2", children: ["Feature Contribution Waterfall & Attribution", _jsx(Badge, { variant: "success", size: "sm", children: "Additive SHAP-Equivalent" })] }), _jsx("p", { className: "text-xs text-[#94A3B8] font-mono", children: "Step-by-step breakdown of how raw features and weights accumulate to form final confidence" })] })] }) }), _jsx(Badge, { variant: "intelligence", size: "md", children: "Final Score: 98.42%" })] }), _jsx("div", { className: "space-y-3 font-mono", children: waterfallSteps.map(step => (_jsxs(Card, { className: "p-4 rounded-xl border border-[#1E293B] bg-[#0F172A] flex flex-wrap items-center justify-between gap-4 hover:border-cyan-500/40 transition-all", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "w-8 h-8 rounded-lg bg-[#131D35] border border-[#1E293B] flex items-center justify-center text-xs font-bold text-cyan-400", children: ["0", step.step] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs font-bold text-white", children: step.feature }), _jsxs("span", { className: "text-[11px] text-[#64748B]", children: ["Weight: ", step.weight, " \u2022 Raw Value: ", step.value] })] })] }), _jsxs("div", { className: "flex items-center gap-6 text-xs", children: [_jsxs("div", { className: "text-right", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "CONTRIBUTION" }), _jsx("span", { className: `font-bold ${step.contribution.startsWith('+') ? 'text-emerald-400' : 'text-amber-400'}`, children: step.contribution })] }), _jsxs("div", { className: "text-right min-w-[80px]", children: [_jsx("span", { className: "text-[10px] text-[#64748B] block", children: "RUNNING TOTAL" }), _jsx("span", { className: "text-cyan-400 font-extrabold", children: step.runningTotal })] })] })] }, step.step))) })] }));
};
