"""
Autonomous Hypothesis Model (Phase 86C)
======================================
Formal representation of autonomously synthesized scientific hypotheses.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from research_validation.provenance.hashing import hash_canonical_json


@dataclass(frozen=True)
class ScientificHypothesis:
    """Formal hypothesis generated by autonomous reasoning."""
    hypothesis_id: str
    title: str
    statement: str
    premise: str
    proposed_mechanism: str
    expected_outcome: str
    confidence_level: float  # 0.0 to 1.0 prior confidence
    risk_score: float        # 0.0 (safe) to 1.0 (high risk of failure)
    impact_score: float      # 0.0 to 1.0
    required_datasets: List[str]
    required_benchmarks: List[str]
    estimated_runtime_sec: float
    supporting_evidence_nodes: List[str]
    created_at_utc: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    hypothesis_digest_sha256: str = field(default="")

    def compute_digest(self) -> str:
        payload = {
            "hypothesis_id": self.hypothesis_id,
            "title": self.title,
            "statement": self.statement,
            "premise": self.premise,
            "mechanism": self.proposed_mechanism,
            "expected_outcome": self.expected_outcome,
            "confidence": self.confidence_level,
            "risk": self.risk_score,
            "impact": self.impact_score,
            "datasets": sorted(self.required_datasets),
        }
        return hash_canonical_json(payload)
