import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { workforceApiClient } from '../../services/workforceApiClient';
import { Database, Scale } from 'lucide-react';
export const CollectiveIntelligenceMonitor = () => {
    const [memories, setMemories] = useState([]);
    const [conflicts, setConflicts] = useState([]);
    useEffect(() => {
        workforceApiClient.getCollectiveMemories().then(setMemories);
        workforceApiClient.getConflicts().then(setConflicts);
    }, []);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-slate-900/60 p-5 rounded-2xl border border-slate-800", children: [_jsxs("h1", { className: "text-2xl font-bold text-white flex items-center gap-3", children: [_jsx("span", { className: "p-2 bg-sky-500/20 text-sky-400 rounded-xl", children: "\uD83E\uDDE0" }), "Collective Intelligence & Conflict Resolution"] }), _jsx("p", { className: "text-slate-400 text-sm mt-1", children: "Shared Organizational Knowledge, Cross-Department Protocols, and Automated Dispute Arbitration" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsxs("h3", { className: "text-base font-bold text-white mb-4 flex items-center gap-2", children: [_jsx(Database, { className: "w-4 h-4 text-indigo-400" }), " Collective Memory Records"] }), _jsx("div", { className: "space-y-3", children: memories.map((m) => (_jsxs("div", { className: "p-4 bg-slate-950/60 rounded-xl border border-slate-800", children: [_jsxs("div", { className: "flex justify-between items-start mb-1", children: [_jsx("div", { className: "text-sm font-bold text-white", children: m.title }), _jsx(Badge, { variant: "outline", children: m.scope })] }), _jsx("p", { className: "text-xs text-slate-300 mb-2", children: m.content }), _jsxs("div", { className: "text-[10px] text-slate-500", children: ["Author: ", m.author_employee_id, " \u2022 Trust Weight: ", m.trust_weight] })] }, m.id))) })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsxs("h3", { className: "text-base font-bold text-white mb-4 flex items-center gap-2", children: [_jsx(Scale, { className: "w-4 h-4 text-amber-400" }), " Conflict Resolution Ledger"] }), _jsx("div", { className: "space-y-3", children: conflicts.map((c) => (_jsxs("div", { className: "p-4 bg-slate-950/60 rounded-xl border border-slate-800", children: [_jsxs("div", { className: "flex justify-between items-start mb-1", children: [_jsx("div", { className: "text-sm font-bold text-white", children: c.dispute_subject }), _jsx(Badge, { variant: "default", children: c.status })] }), _jsxs("div", { className: "text-xs text-slate-400 my-1", children: ["Parties: ", _jsx("strong", { className: "text-indigo-300", children: c.party_a_id }), " vs ", _jsx("strong", { className: "text-indigo-300", children: c.party_b_id }), " (Mediator: ", c.mediator_employee_id, ")"] }), _jsx("p", { className: "text-xs text-emerald-400 mb-2 font-medium", children: c.resolution_summary }), _jsxs("div", { className: "text-[10px] text-slate-500", children: ["Agreements: ", c.binding_agreements.join(', ')] })] }, c.id))) })] })] })] }));
};
