import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { Card } from '../../components/ui/Card';
import { workforceApiClient } from '../../services/workforceApiClient';
import { Activity, Flame, HeartHandshake } from 'lucide-react';
export const PerformanceAnalytics = () => {
    const [metric, setMetric] = useState(null);
    useEffect(() => {
        workforceApiClient.getPerformance().then(setMetric);
    }, []);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-slate-900/60 p-5 rounded-2xl border border-slate-800", children: [_jsxs("h1", { className: "text-2xl font-bold text-white flex items-center gap-3", children: [_jsx("span", { className: "p-2 bg-rose-500/20 text-rose-400 rounded-xl", children: "\uD83D\uDCCA" }), "Workforce Performance Analytics"] }), _jsx("p", { className: "text-slate-400 text-sm mt-1", children: "Fleet Productivity, Burnout Risk, Collaboration Metrics, and Innovation Speed" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsxs("div", { className: "flex justify-between items-center text-xs text-slate-400", children: [_jsx("span", { children: "Fleet Utilization" }), _jsx(Activity, { className: "w-4 h-4 text-indigo-400" })] }), _jsxs("div", { className: "text-3xl font-bold text-white mt-2", children: [Math.round((metric?.workforce_utilization_rate ?? 0.83) * 100), "%"] }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "Active / Total Capacity" })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsxs("div", { className: "flex justify-between items-center text-xs text-slate-400", children: [_jsx("span", { children: "Collaboration Index" }), _jsx(HeartHandshake, { className: "w-4 h-4 text-emerald-400" })] }), _jsx("div", { className: "text-3xl font-bold text-emerald-400 mt-2", children: metric?.collaboration_index ?? 0.94 }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "Cross-Agent Consensus Velocity" })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsxs("div", { className: "flex justify-between items-center text-xs text-slate-400", children: [_jsx("span", { children: "Burnout Risk Index" }), _jsx(Flame, { className: "w-4 h-4 text-amber-400" })] }), _jsxs("div", { className: "text-3xl font-bold text-amber-400 mt-2", children: [Math.round((metric?.workforce_burnout_risk ?? 0.04) * 100), "%"] }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "Safe Load Margins" })] })] })] }));
};
