import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { Card } from '../../components/ui/Card';
import { workforceApiClient } from '../../services/workforceApiClient';
export const ResourceEconomyDashboard = () => {
    const [econ, setEcon] = useState(null);
    useEffect(() => {
        workforceApiClient.getEconomics().then(setEcon);
    }, []);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-slate-900/60 p-5 rounded-2xl border border-slate-800", children: [_jsxs("h1", { className: "text-2xl font-bold text-white flex items-center gap-3", children: [_jsx("span", { className: "p-2 bg-emerald-500/20 text-emerald-400 rounded-xl", children: "\uD83D\uDCB0" }), "Resource Economy & Budget Allocation"] }), _jsx("p", { className: "text-slate-400 text-sm mt-1", children: "Compute (GPU/CPU), Token Consumption, and Enterprise Value Return" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4", children: [_jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsx("div", { className: "text-xs text-slate-400 font-semibold uppercase", children: "Total Budget (USD)" }), _jsxs("div", { className: "text-2xl font-bold text-white mt-1", children: ["$", (econ?.total_budget_usd ?? 35000).toLocaleString()] }), _jsxs("div", { className: "text-xs text-emerald-400 mt-1", children: ["Spent: $", (econ?.total_spent_usd ?? 18250).toLocaleString()] })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsx("div", { className: "text-xs text-slate-400 font-semibold uppercase", children: "GPU Hours Used" }), _jsxs("div", { className: "text-2xl font-bold text-indigo-400 mt-1", children: [econ?.used_gpu_hours ?? 1140, " hrs"] }), _jsxs("div", { className: "text-xs text-slate-400 mt-1", children: ["of ", econ?.allocated_gpu_hours ?? 2000, " hrs"] })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsx("div", { className: "text-xs text-slate-400 font-semibold uppercase", children: "Token Pool" }), _jsxs("div", { className: "text-2xl font-bold text-purple-400 mt-1", children: [((econ?.used_tokens ?? 540000000) / 1e6).toFixed(0), "M"] }), _jsxs("div", { className: "text-xs text-slate-400 mt-1", children: ["of ", ((econ?.allocated_tokens ?? 1000000000) / 1e6).toFixed(0), "M tokens"] })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsx("div", { className: "text-xs text-slate-400 font-semibold uppercase", children: "Value Multiplier (ROI)" }), _jsxs("div", { className: "text-2xl font-bold text-amber-400 mt-1", children: [econ?.efficiency_roi_ratio ?? 5.4, "x"] }), _jsx("div", { className: "text-xs text-slate-400 mt-1", children: "Net Productivity Gain" })] })] }), _jsxs(Card, { className: "p-5 bg-slate-900/50 border-slate-800", children: [_jsx("h3", { className: "text-base font-bold text-white mb-3", children: "Autonomous Reallocation Directives" }), _jsx("ul", { className: "space-y-2", children: (econ?.reallocation_recommendations ?? []).map((r, idx) => (_jsxs("li", { className: "p-3 bg-slate-950/60 rounded-xl border border-slate-800 text-xs text-slate-300 flex items-center gap-2", children: [_jsx("span", { className: "text-emerald-400 font-bold", children: "\u26A1" }), " ", r] }, idx))) })] })] }));
};
