import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
export const ConnectorCenter = () => {
    const connectors = [
        { id: 'CONN-GMAIL', name: 'Google Workspace Gmail', category: 'Communication', status: 'Connected', latency: '32ms', calls24h: '1,420' },
        { id: 'CONN-OUTLOOK', name: 'Microsoft 365 Exchange / Outlook', category: 'Communication', status: 'Connected', latency: '28ms', calls24h: '890' },
        { id: 'CONN-SLACK', name: 'Slack Enterprise Grid', category: 'Communication', status: 'Connected', latency: '18ms', calls24h: '3,120' },
        { id: 'CONN-TEAMS', name: 'Microsoft Teams Adaptive Cards', category: 'Communication', status: 'Connected', latency: '22ms', calls24h: '650' },
        { id: 'CONN-GDRIVE', name: 'Google Drive & Cloud Storage', category: 'Storage', status: 'Connected', latency: '45ms', calls24h: '2,400' },
        { id: 'CONN-SHAREPOINT', name: 'Microsoft SharePoint Online', category: 'Storage', status: 'Connected', latency: '52ms', calls24h: '1,100' },
        { id: 'CONN-QUICKBOOKS', name: 'Intuit QuickBooks Online', category: 'Business Systems', status: 'Connected', latency: '64ms', calls24h: '4,200' },
        { id: 'CONN-SALESFORCE', name: 'Salesforce Enterprise CRM', category: 'Business Systems', status: 'Connected', latency: '48ms', calls24h: '1,800' },
        { id: 'CONN-JIRA', name: 'Atlassian Jira Service Management', category: 'Business Systems', status: 'Connected', latency: '38ms', calls24h: '950' },
        { id: 'CONN-WEBHOOK', name: 'Custom REST Webhook Gateway', category: 'API & ERP', status: 'Connected', latency: '12ms', calls24h: '7,800' },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 rounded-2xl bg-gradient-to-r from-[#0F172A] to-[#1E293B] border border-[#334155]/60 shadow-xl", children: [_jsxs("div", { children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: "INTEGRATION HUB" }), _jsx("h1", { className: "text-2xl font-black text-white mt-1", children: "Enterprise Connector Center" }), _jsx("p", { className: "text-sm text-[#94A3B8]", children: "Pre-authenticated connectors for seamless document ingestion, communication, and ERP dispatch." })] }), _jsx(Button, { variant: "primary", size: "md", children: "+ Add Custom Webhook" })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: connectors.map((conn) => (_jsxs("div", { className: "p-5 rounded-2xl bg-[#0F172A]/80 border border-[#1E293B] shadow-xl space-y-4 hover:border-[#00D2FF]/40 transition-all", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Badge, { variant: "default", size: "sm", children: conn.category }), _jsxs("span", { className: "text-[10px] font-mono text-emerald-400 bg-emerald-950/40 px-2 py-0.5 rounded border border-emerald-800/40", children: ["\u25CF ", conn.status] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-bold text-white", children: conn.name }), _jsx("span", { className: "text-xs text-[#64748B] font-mono", children: conn.id })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 py-2 border-t border-[#1E293B] text-xs", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[#94A3B8] block text-[10px]", children: "Avg Latency" }), _jsx("span", { className: "font-mono text-cyan-400 font-bold", children: conn.latency })] }), _jsxs("div", { children: [_jsx("span", { className: "text-[#94A3B8] block text-[10px]", children: "24h Volume" }), _jsxs("span", { className: "font-mono text-white font-bold", children: [conn.calls24h, " calls"] })] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { variant: "secondary", size: "sm", className: "w-full", children: "Test Ping" }), _jsx(Button, { variant: "outline", size: "sm", className: "w-full", children: "Configure" })] })] }, conn.id))) })] }));
};
