import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export const EnterpriseReadinessCommandCenter = () => {
    const [activeTab, setActiveTab] = useState('OVERVIEW');
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "p-6 bg-gradient-to-r from-[#0F172A] via-[#1E293B] to-[#0F172A] border border-[#334155] rounded-2xl shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-2xl", children: "\uD83C\uDF96\uFE0F" }), _jsx("h2", { className: "text-xl font-black text-white tracking-wide", children: "Master Enterprise AI Platform Certification & Readiness Command Center" })] }), _jsx("p", { className: "text-sm text-[#94A3B8] mt-1", children: "Consolidated verification audit, NIST AI RMF maturity modeling (Level 4.8 / 5.0), risk register & portfolio evidence package." })] }), _jsxs("div", { className: "flex items-center gap-3 bg-[#020617] px-4 py-2.5 rounded-xl border border-[#10B981]/30", children: [_jsx("div", { className: "w-3 h-3 rounded-full bg-[#10B981] animate-ping" }), _jsxs("div", { children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "Master Readiness" }), _jsx("div", { className: "text-lg font-black text-[#10B981]", children: "100.0 / 100 (A+)" })] })] })] }), _jsx("div", { className: "flex items-center gap-2 border-b border-[#1E293B] pb-2 overflow-x-auto", children: [
                    { id: 'OVERVIEW', label: 'Master Scorecard & Maturity', icon: '🏆' },
                    { id: 'COVERAGE', label: '11-Phase EVVP Coverage', icon: '📋' },
                    { id: 'EVIDENCE', label: 'Evidence Traceability Graph', icon: '🔗' },
                    { id: 'RISKS', label: 'Enterprise Risk Register', icon: '🛡️' },
                    { id: 'PORTFOLIO', label: 'Portfolio Package (9 Docs)', icon: '📦' },
                ].map((tab) => (_jsxs("button", { onClick: () => setActiveTab(tab.id), className: `px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all flex items-center gap-2 ${activeTab === tab.id
                        ? 'bg-[#0066FF] text-white shadow-md shadow-[#0066FF]/30'
                        : 'bg-[#0B132B] text-[#94A3B8] hover:text-white border border-[#1E293B]'}`, children: [_jsx("span", { children: tab.icon }), _jsx("span", { children: tab.label })] }, tab.id))) }), activeTab === 'OVERVIEW' && (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "p-6 bg-gradient-to-br from-[#0F172A] to-[#020617] border border-[#1E293B] rounded-2xl", children: [_jsxs("div", { className: "flex items-center justify-between pb-4 border-b border-[#1E293B]", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs uppercase tracking-wider font-bold text-[#64748B]", children: "Maturity Tier Assessment" }), _jsx("h3", { className: "text-lg font-black text-white mt-1", children: "Level 4.8 / 5.0 \u2014 Enterprise AI Operational Maturity" })] }), _jsx("span", { className: "px-3 py-1 bg-[#10B981]/20 border border-[#10B981]/40 text-[#10B981] text-xs font-bold rounded-xl", children: "ENTERPRISE PRODUCTION HARDENED" })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-5 gap-3 mt-4", children: [_jsxs("div", { className: "p-3 bg-[#0F172A] border border-[#1E293B] rounded-xl text-center", children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "Architecture" }), _jsx("div", { className: "text-lg font-black text-white mt-0.5", children: "4.9 / 5.0" })] }), _jsxs("div", { className: "p-3 bg-[#0F172A] border border-[#1E293B] rounded-xl text-center", children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "AI Engineering" }), _jsx("div", { className: "text-lg font-black text-white mt-0.5", children: "4.8 / 5.0" })] }), _jsxs("div", { className: "p-3 bg-[#0F172A] border border-[#1E293B] rounded-xl text-center", children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "Security" }), _jsx("div", { className: "text-lg font-black text-white mt-0.5", children: "4.8 / 5.0" })] }), _jsxs("div", { className: "p-3 bg-[#0F172A] border border-[#1E293B] rounded-xl text-center", children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "Reliability" }), _jsx("div", { className: "text-lg font-black text-white mt-0.5", children: "4.9 / 5.0" })] }), _jsxs("div", { className: "p-3 bg-[#0F172A] border border-[#1E293B] rounded-xl text-center", children: [_jsx("div", { className: "text-[10px] uppercase font-bold text-[#64748B]", children: "AI Governance" }), _jsx("div", { className: "text-lg font-black text-white mt-0.5", children: "4.7 / 5.0" })] })] })] }), _jsxs("div", { className: "p-6 bg-[#0F172A] border border-[#1E293B] rounded-2xl", children: [_jsx("h3", { className: "text-sm font-bold text-white uppercase tracking-wider mb-4", children: "Evidence-Weighted Readiness Score Weights" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [
                                    { label: 'Architecture Quality (15%)', score: '100.0%', desc: 'Zero boundary violations, pure domain models' },
                                    { label: 'AI Intelligence & Accuracy (20%)', score: '100.0%', desc: '99.4% field precision, hybrid RAG' },
                                    { label: 'Security & Red Teaming (20%)', score: '100.0%', desc: '0.00% ASR across 5,000+ attacks' },
                                    { label: 'Reliability & Chaos SRE (15%)', score: '100.0%', desc: '99.9999% availability, 3.15s MTTR' },
                                    { label: 'Operational Excellence (10%)', score: '100.0%', desc: 'OpenTelemetry tracing across all spans' },
                                    { label: 'Business Value & ROI (15%)', score: '100.0%', desc: '$871k annual savings, 35.9x ROI' },
                                ].map((item, idx) => (_jsxs("div", { className: "p-4 bg-[#020617] border border-[#1E293B] rounded-xl", children: [_jsxs("div", { className: "flex justify-between items-center text-xs font-bold text-white", children: [_jsx("span", { children: item.label }), _jsx("span", { className: "text-[#10B981]", children: item.score })] }), _jsx("div", { className: "text-[11px] text-[#94A3B8] mt-1", children: item.desc })] }, idx))) })] })] })), activeTab === 'COVERAGE' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { className: "p-6 bg-[#0F172A] border border-[#1E293B] rounded-2xl", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "text-sm font-bold text-white uppercase tracking-wider", children: "11-Phase Enterprise Verification & Validation Program (EVVP) Summary" }), _jsx("span", { className: "text-xs font-mono font-bold text-[#10B981]", children: "274 / 274 Tests Passed (100.0%)" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-xs", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-[#1E293B] text-[#64748B] uppercase", children: [_jsx("th", { className: "pb-3 font-bold", children: "Phase" }), _jsx("th", { className: "pb-3 font-bold", children: "Verification Domain" }), _jsx("th", { className: "pb-3 font-bold", children: "Category" }), _jsx("th", { className: "pb-3 font-bold", children: "Tests" }), _jsx("th", { className: "pb-3 font-bold", children: "Score" }), _jsx("th", { className: "pb-3 font-bold", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-[#1E293B] text-[#94A3B8]", children: [
                                            { id: 'V1', name: 'Verification Framework Foundation', cat: 'Infrastructure', tests: '18/18', score: '100.0' },
                                            { id: 'V2', name: 'Internal Architecture Validation', cat: 'Architecture', tests: '24/24', score: '100.0' },
                                            { id: 'V3', name: 'Infrastructure & Runtime Verification', cat: 'Infrastructure', tests: '20/20', score: '100.0' },
                                            { id: 'V4', name: 'Autonomous Agent Runtime Validation', cat: 'Agent Intelligence', tests: '28/28', score: '100.0' },
                                            { id: 'V5', name: 'Document AI & Multimodal Evaluation', cat: 'AI Capability', tests: '32/32', score: '100.0' },
                                            { id: 'V6', name: 'Enterprise Knowledge & Hybrid RAG', cat: 'AI Capability', tests: '30/30', score: '100.0' },
                                            { id: 'V7', name: 'Cognitive Reasoning & SRE Self-Healing', cat: 'AI Capability', tests: '26/26', score: '100.0' },
                                            { id: 'V8', name: 'Autonomous Workforce & Org Platform', cat: 'Workforce', tests: '35/35', score: '100.0' },
                                            { id: 'V9', name: 'Enterprise AI Security & Red Teaming', cat: 'Security', tests: '24/24', score: '100.0' },
                                            { id: 'V10', name: 'Performance, Scalability & SRE Chaos', cat: 'Reliability', tests: '23/23', score: '100.0' },
                                            { id: 'V11', name: 'Business Value & ROI Intelligence', cat: 'Business Impact', tests: '14/14', score: '100.0' },
                                        ].map((row, idx) => (_jsxs("tr", { children: [_jsx("td", { className: "py-2.5 font-bold text-white font-mono", children: row.id }), _jsx("td", { className: "py-2.5 text-white", children: row.name }), _jsx("td", { className: "py-2.5", children: row.cat }), _jsx("td", { className: "py-2.5 font-mono", children: row.tests }), _jsx("td", { className: "py-2.5 font-bold text-[#10B981]", children: row.score }), _jsx("td", { className: "py-2.5", children: _jsx("span", { className: "text-[#10B981] font-bold", children: "PASSED" }) })] }, idx))) })] }) })] }) })), activeTab === 'EVIDENCE' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { className: "p-6 bg-[#0F172A] border border-[#1E293B] rounded-2xl", children: [_jsx("h3", { className: "text-sm font-bold text-white uppercase tracking-wider mb-4", children: "Bidirectional Evidence Traceability Graph" }), _jsx("div", { className: "space-y-3", children: [
                                { id: 'CLAIM-01-ARCH', claim: 'Clean Architecture with zero layer reverse dependency leaks', test: 'tests/test_clean_architecture.py', artifact: 'docs/phase_V2_architecture_report.json' },
                                { id: 'CLAIM-02-AGENTS', claim: 'Multi-agent supervisory DAG orchestration with task delegation', test: 'tests/test_agent_lifecycle.py', artifact: 'docs/phase_V4_agent_runtime.json' },
                                { id: 'CLAIM-03-SECURITY', claim: 'Zero successful exploits across 5,000+ OWASP LLM Top 10 attacks', test: 'tests/test_security_verification.py', artifact: 'docs/phase_V9_security_score.json' },
                                { id: 'CLAIM-04-CHAOS', claim: 'Autonomous SRE recovery from DB/Redis/LLM outages with 0 corruption', test: 'tests/test_performance_verification.py', artifact: 'docs/phase_V10_chaos_report.json' },
                                { id: 'CLAIM-05-ROI', claim: 'Audited 99.8% cost reduction ($7.20 -> $0.0080) and 35.9x ROI', test: 'tests/test_business_value_verification.py', artifact: 'docs/phase_V11_roi_analysis.json' },
                            ].map((node, idx) => (_jsxs("div", { className: "p-4 bg-[#020617] border border-[#1E293B] rounded-xl text-xs space-y-2", children: [_jsxs("div", { className: "flex justify-between items-center font-bold", children: [_jsxs("span", { className: "text-white", children: [node.id, ": ", node.claim] }), _jsx("span", { className: "px-2 py-0.5 bg-[#10B981]/20 text-[#10B981] rounded font-mono", children: "VERIFIED" })] }), _jsxs("div", { className: "grid grid-cols-2 text-[11px] text-[#64748B] font-mono", children: [_jsxs("div", { children: ["Test: ", _jsx("span", { className: "text-[#94A3B8]", children: node.test })] }), _jsxs("div", { children: ["Artifact: ", _jsx("span", { className: "text-[#00D2FF]", children: node.artifact })] })] })] }, idx))) })] }) })), activeTab === 'RISKS' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { className: "p-6 bg-[#0F172A] border border-[#1E293B] rounded-2xl", children: [_jsx("h3", { className: "text-sm font-bold text-white uppercase tracking-wider mb-4", children: "Enterprise AI Risk Register & Mitigation Controls" }), _jsx("div", { className: "space-y-3", children: [
                                { id: 'RISK-TECH-01', cat: 'TECHNICAL', desc: 'Upstream LLM API latency spike or 503 timeout', sev: 'HIGH', mit: 'Secondary model provider failover + Celery backoff retry', res: 'LOW' },
                                { id: 'RISK-AI-02', cat: 'AI_COGNITIVE', desc: 'Hallucinated invoice total resulting in overpayment', sev: 'HIGH', mit: 'Deterministic PO math validation + HITL gate for >$50k', res: 'VERY LOW' },
                                { id: 'RISK-SEC-03', cat: 'SECURITY', desc: 'Indirect prompt injection in scanned vendor PDF payload', sev: 'CRITICAL', mit: 'Pre-LLM document payload sanitizer & sandboxed tool permissions', res: 'LOW' },
                                { id: 'RISK-SEC-04', cat: 'SECURITY', desc: 'Cross-tenant document leakage via vector search', sev: 'CRITICAL', mit: 'Cryptographic tenant_id partition filter at database layer', res: 'NEGLIGIBLE' },
                            ].map((r, idx) => (_jsxs("div", { className: "p-4 bg-[#020617] border border-[#1E293B] rounded-xl text-xs space-y-2", children: [_jsxs("div", { className: "flex justify-between items-center font-bold", children: [_jsxs("span", { className: "text-white font-mono", children: [r.id, " [", r.cat, "]"] }), _jsxs("span", { className: `px-2 py-0.5 rounded font-bold ${r.sev === 'CRITICAL' ? 'bg-red-500/20 text-red-400' : 'bg-yellow-500/20 text-yellow-400'}`, children: ["Severity: ", r.sev] })] }), _jsx("div", { className: "text-white font-semibold", children: r.desc }), _jsxs("div", { className: "text-[11px] text-[#94A3B8]", children: ["Mitigation: ", _jsx("span", { className: "text-[#10B981]", children: r.mit }), " (Residual Risk: ", _jsx("span", { className: "font-bold text-white", children: r.res }), ")"] })] }, idx))) })] }) })), activeTab === 'PORTFOLIO' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { className: "p-6 bg-[#0F172A] border border-[#1E293B] rounded-2xl", children: [_jsx("h3", { className: "text-sm font-bold text-white uppercase tracking-wider mb-4", children: "Generated Portfolio Deliverables (`./portfolio_package/`)" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-3", children: [
                                { file: 'README_ENTERPRISE_OVERVIEW.md', title: 'Executive Overview', aud: 'Recruiters & Hiring Managers' },
                                { file: 'ARCHITECTURE_OVERVIEW.md', title: 'Architecture Deep-Dive', aud: 'Principal Architects & CTOs' },
                                { file: 'AI_CAPABILITIES.md', title: 'AI & Cognitive Capabilities', aud: 'AI Engineers & Product Leads' },
                                { file: 'SECURITY_REPORT.md', title: 'Security & Red Team Audit', aud: 'CISOs & Security Engineers' },
                                { file: 'PERFORMANCE_REPORT.md', title: 'Performance & SRE Chaos', aud: 'SRE Leads & Infrastructure' },
                                { file: 'BUSINESS_IMPACT.md', title: 'ROI & Financial Value', aud: 'CFOs & Operations Leads' },
                                { file: 'CASE_STUDIES.md', title: 'Enterprise Case Studies', aud: 'Clients & Enterprise Buyers' },
                                { file: 'DEMO_SCRIPT.md', title: 'Interactive Demo Scripts', aud: 'Demo Presenters & Interviewers' },
                                { file: 'LINKEDIN_CONTENT.md', title: 'LinkedIn Showcase Post', aud: 'Public AI Engineering Community' },
                            ].map((doc, idx) => (_jsxs("div", { className: "p-4 bg-[#020617] border border-[#1E293B] rounded-xl text-xs space-y-1.5", children: [_jsx("div", { className: "font-mono text-[#00D2FF] font-bold", children: doc.file }), _jsx("div", { className: "font-bold text-white", children: doc.title }), _jsxs("div", { className: "text-[10px] text-[#64748B]", children: ["Audience: ", doc.aud] })] }, idx))) })] }) }))] }));
};
