import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
export const TrustCenter = () => {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 rounded-2xl bg-gradient-to-r from-[#0F172A] to-[#1E293B] border border-[#334155]/60 shadow-xl", children: [_jsxs("div", { children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: "SECURITY & COMPLIANCE PORTAL" }), _jsx("h1", { className: "text-2xl font-black text-white mt-1", children: "Enterprise AI Trust Center" }), _jsx("p", { className: "text-sm text-[#94A3B8]", children: "Cryptographic tenant isolation, zero training data retention, and immutable audit ledgers." })] }), _jsx(Badge, { variant: "success", size: "md", children: "100 / 100 Trust Score" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "p-6 rounded-2xl bg-[#0F172A]/80 border border-[#1E293B] shadow-xl space-y-4", children: [_jsx("h2", { className: "text-base font-bold text-white", children: "Regulatory Frameworks" }), _jsx("div", { className: "space-y-3", children: [
                                    { name: 'SOC 2 Type II Certified', desc: 'Continuous security & availability controls', badge: 'Certified' },
                                    { name: 'HIPAA Security Rule', desc: 'Encrypted ePHI with BAA guarantees', badge: 'Compliant' },
                                    { name: 'GDPR Article 28 (DPA)', desc: 'Right to erasure & EU regional tenancy', badge: 'Compliant' },
                                    { name: 'ISO/IEC 27001', desc: 'Information security management system', badge: 'Aligned' },
                                ].map((comp, idx) => (_jsxs("div", { className: "p-3.5 rounded-xl bg-[#0A0F1D] border border-[#1E293B] flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs font-bold text-white block", children: comp.name }), _jsx("span", { className: "text-[11px] text-[#94A3B8]", children: comp.desc })] }), _jsx("span", { className: "text-[10px] font-mono text-emerald-400 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-800/40", children: comp.badge })] }, idx))) })] }), _jsxs("div", { className: "lg:col-span-2 p-6 rounded-2xl bg-[#0F172A]/80 border border-[#1E293B] shadow-xl space-y-5", children: [_jsx("h2", { className: "text-base font-bold text-white", children: "AI Model Governance & Guardrails" }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: [_jsxs("div", { className: "p-4 rounded-xl bg-[#0A0F1D] border border-[#1E293B] space-y-2", children: [_jsx("span", { className: "text-xs font-bold text-cyan-400", children: "Zero Data Retention (ZTR)" }), _jsx("p", { className: "text-xs text-[#94A3B8] leading-relaxed", children: "Enterprise API contracts guarantee that customer documents and prompts are never used for model training or retained on third-party servers." })] }), _jsxs("div", { className: "p-4 rounded-xl bg-[#0A0F1D] border border-[#1E293B] space-y-2", children: [_jsx("span", { className: "text-xs font-bold text-emerald-400", children: "Cryptographic Partitioning" }), _jsx("p", { className: "text-xs text-[#94A3B8] leading-relaxed", children: "Each enterprise tenant uses isolated KMS encryption keys (AES-256-GCM) with strict Row-Level Security across all vector indices and databases." })] }), _jsxs("div", { className: "p-4 rounded-xl bg-[#0A0F1D] border border-[#1E293B] space-y-2", children: [_jsx("span", { className: "text-xs font-bold text-purple-400", children: "Prompt Injection Defenses" }), _jsx("p", { className: "text-xs text-[#94A3B8] leading-relaxed", children: "100% defense against indirect prompt injections and jailbreaks through automated AST input sanitization and dual-stage guardrail agents." })] }), _jsxs("div", { className: "p-4 rounded-xl bg-[#0A0F1D] border border-[#1E293B] space-y-2", children: [_jsx("span", { className: "text-xs font-bold text-amber-400", children: "Immutable Audit Ledger" }), _jsx("p", { className: "text-xs text-[#94A3B8] leading-relaxed", children: "Every agent step, tool invocation, and human review decision is cryptographically signed and logged with SHA-256 tamper-evident checksums." })] })] })] })] })] }));
};
