"""
Domain models for SOLID Principle Automated Verification System (PART 2C).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
from typing import Any, Dict, List, Optional, Set, Tuple, Union


class SolidPrinciple(str, Enum):
    SRP = "SINGLE_RESPONSIBILITY"
    OCP = "OPEN_CLOSED"
    LSP = "LISKOV_SUBSTITUTION"
    ISP = "INTERFACE_SEGREGATION"
    DIP = "DEPENDENCY_INVERSION"


class SolidViolationSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SolidCertificationBand(str, Enum):
    ENTERPRISE_DESIGN_QUALITY = "ENTERPRISE_DESIGN_QUALITY"  # 95-100
    PRODUCTION_QUALITY = "PRODUCTION_QUALITY"                # 90-94
    ACCEPTABLE = "ACCEPTABLE"                                # 80-89
    TECHNICAL_DEBT_WARNING = "TECHNICAL_DEBT_WARNING"        # 70-79
    FAILED = "FAILED"                                        # < 70


@dataclass
class ClassDesignMetrics:
    """Chidamber & Kemerer (CK) and SOLID Object-Oriented Metrics for a single class."""
    class_name: str
    file_path: str
    line_count: int
    method_count: int
    attribute_count: int
    constructor_param_count: int
    wmc_weighted_methods: int  # Cyclomatic complexity sum
    cbo_coupling_between_objects: int
    lcom_lack_of_cohesion: float  # 0.0 (high cohesion) to 1.0 (no cohesion)
    rfc_response_for_class: int
    dit_depth_of_inheritance: int
    noc_number_of_children: int
    detected_responsibilities: List[str] = field(default_factory=list)
    has_type_switch_violation: bool = False
    has_unsupported_operation_override: bool = False
    has_direct_instantiation_violation: bool = False


@dataclass
class InterfaceDesignMetrics:
    """Metrics for interfaces / abstract base classes (ISP)."""
    interface_name: str
    file_path: str
    total_methods: int
    implementations_count: int
    avg_usage_ratio: float  # Used methods / Total methods
    is_oversized: bool = False


@dataclass
class SolidViolation:
    """Individual SOLID design violation."""
    violation_id: str
    principle: SolidPrinciple
    class_name: str
    file_path: str
    line_number: int
    severity: SolidViolationSeverity
    message: str
    suggested_refactoring: str


@dataclass
class PrincipleScore:
    """Score breakdown for a specific SOLID principle."""
    principle: SolidPrinciple
    weight: float
    raw_score: float  # 0 to 100
    weighted_score: float
    violations_count: int = 0


@dataclass
class SolidQualityScorecard:
    """Consolidated SOLID design quality scorecard."""
    total_score: float  # 0 to 100
    certification_band: SolidCertificationBand
    principle_scores: List[PrincipleScore]
    total_violations_count: int
    critical_violations_count: int
    is_design_certified: bool


@dataclass
class SolidEvidencePackage:
    """Sealed evidence package generated by SOLID verification scan."""
    scan_id: str
    repository_name: str = "DocuTask-Agent"
    commit_sha: str = "HEAD"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    total_classes_analyzed: int = 0
    total_interfaces_analyzed: int = 0
    class_metrics: Dict[str, ClassDesignMetrics] = field(default_factory=dict)
    interface_metrics: Dict[str, InterfaceDesignMetrics] = field(default_factory=dict)
    violations: List[SolidViolation] = field(default_factory=list)
    scorecard: Optional[SolidQualityScorecard] = None
    evidence_sha256: str = ""

    def compute_sha256(self) -> str:
        score = self.scorecard.total_score if self.scorecard else 0.0
        payload = f"{self.scan_id}:{self.timestamp}:{score}:{len(self.violations)}:{self.total_classes_analyzed}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()
