import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Rocket, Activity } from 'lucide-react';
export const DeploymentCenter = () => {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "flex items-center justify-between", children: _jsxs("div", { children: [_jsxs("h1", { className: "text-2xl font-bold text-white flex items-center gap-3", children: [_jsx(Rocket, { className: "w-7 h-7 text-indigo-400" }), "Distributed Deployment & Traffic Routing"] }), _jsx("p", { className: "text-sm text-slate-400 mt-1", children: "Blue-Green and Canary traffic orchestration across Phase 13.18 Distributed Cloud Runtime." })] }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Card, { className: "bg-slate-900/80 border-slate-800", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(CardTitle, { className: "text-base text-white", children: "Canary Release Strategy" }), _jsx(Badge, { variant: "success", children: "PRODUCTION (100%)" })] }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { className: "p-4 bg-slate-950 rounded-lg border border-slate-800 space-y-2", children: [_jsxs("div", { className: "flex justify-between text-xs", children: [_jsx("span", { className: "text-slate-300", children: "Traffic Distribution" }), _jsx("span", { className: "text-emerald-400 font-bold", children: "100% Canary v1.2.0" })] }), _jsx("div", { className: "w-full bg-slate-800 h-2 rounded-full overflow-hidden", children: _jsx("div", { className: "bg-emerald-500 h-2 w-full" }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 text-xs", children: [_jsxs("div", { className: "p-3 bg-slate-800/40 rounded border border-slate-700/50", children: [_jsx("span", { className: "text-slate-400 block text-[10px]", children: "Cluster ID" }), _jsx("span", { className: "text-white font-mono font-medium", children: "cluster_us_east_primary" })] }), _jsxs("div", { className: "p-3 bg-slate-800/40 rounded border border-slate-700/50", children: [_jsx("span", { className: "text-slate-400 block text-[10px]", children: "Instances" }), _jsx("span", { className: "text-cyan-400 font-bold font-mono", children: "8 Active Workers" })] })] })] })] }), _jsxs(Card, { className: "bg-slate-900/80 border-slate-800", children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "text-base text-white flex items-center gap-2", children: [_jsx(Activity, { className: "w-5 h-5 text-indigo-400" }), " Runtime Health & Cluster Metrics"] }) }), _jsx(CardContent, { className: "space-y-3", children: [
                                    { label: 'Mean Response Latency', val: '310 ms', badge: 'success' },
                                    { label: 'Cluster Error Rate', val: '0.02%', badge: 'success' },
                                    { label: 'Distributed Queue Depth', val: '4 messages', badge: 'intelligence' },
                                ].map((m, idx) => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-slate-800/40 rounded border border-slate-700/50", children: [_jsx("span", { className: "text-xs text-slate-300", children: m.label }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-sm font-bold text-white font-mono", children: m.val }), _jsx(Badge, { variant: m.badge, children: "HEALTHY" })] })] }, idx))) })] })] })] }));
};
