import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
import { CornerDownRight } from 'lucide-react';
export const CorrelationExplorerView = () => {
    const correlationId = 'corr-mission-fin-001';
    const traceSteps = [
        { id: 'evt-001', type: 'MissionCreated', actor: 'Operator', time: '14:20:00.120', causationId: 'cause-root', latency: '0ms', depth: 0 },
        { id: 'evt-002', type: 'PlannerStarted', actor: 'ChiefPlanner', time: '14:20:00.350', causationId: 'cause-evt-001', latency: '230ms', depth: 1 },
        { id: 'evt-003', type: 'PlannerFinished', actor: 'ChiefPlanner', time: '14:20:00.890', causationId: 'cause-evt-002', latency: '540ms', depth: 2 },
        { id: 'evt-004', type: 'TaskAssigned', actor: 'DAGScheduler', time: '14:20:01.100', causationId: 'cause-evt-003', latency: '210ms', depth: 3 },
        { id: 'evt-005', type: 'OCRCompleted', actor: 'worker-ocr-01', time: '14:20:01.420', causationId: 'cause-evt-004', latency: '320ms', depth: 4 },
        { id: 'evt-006', type: 'ValidationPassed', actor: 'ScientificValidator', time: '14:20:01.750', causationId: 'cause-evt-005', latency: '330ms', depth: 5 },
        { id: 'evt-007', type: 'MissionCompleted', actor: 'MissionCommander', time: '14:20:02.100', causationId: 'cause-evt-006', latency: '350ms', depth: 6 },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-border/40 pb-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Correlation & Distributed Trace Explorer" }), _jsx(Badge, { variant: "intelligence", size: "sm", children: "Causation DAG" })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-1", children: "Visualizes distributed parent-child causation trees and end-to-end execution lineages." })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsx(Badge, { variant: "success", size: "md", children: "Trace Verified: 7 Nodes Linked" }) })] }), _jsxs(Card, { className: "p-5 border-border/60 space-y-4", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/40 pb-3", children: [_jsxs("div", { children: [_jsx("div", { className: "text-xs font-semibold text-muted-foreground uppercase", children: "Correlation Identifier" }), _jsx("div", { className: "text-sm font-mono font-bold text-primary mt-0.5", children: correlationId })] }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-xs text-muted-foreground", children: "Total Span Duration" }), _jsx("div", { className: "text-sm font-mono font-bold text-emerald-400", children: "1.98 seconds" })] })] }), _jsx("div", { className: "space-y-2 pt-2", children: traceSteps.map((step, idx) => (_jsxs("div", { className: "flex items-center gap-3 p-3 rounded-lg bg-muted/40 border border-border/30 font-mono text-xs", style: { marginLeft: `${step.depth * 14}px` }, children: [_jsx(CornerDownRight, { className: "w-4 h-4 text-muted-foreground shrink-0" }), _jsxs(Badge, { variant: "intelligence", size: "sm", children: ["Step ", idx + 1] }), _jsx("span", { className: "font-bold text-foreground", children: step.type }), _jsx("span", { className: "text-muted-foreground", children: "\u2022" }), _jsx("span", { className: "text-muted-foreground text-[11px]", children: step.actor }), _jsx("span", { className: "text-muted-foreground", children: "\u2022" }), _jsxs("span", { className: "text-primary text-[11px]", children: ["+", step.latency] }), _jsx("span", { className: "ml-auto text-[10px] text-muted-foreground", children: step.id })] }, step.id))) })] })] }));
};
