"""
Domain models for Clean Architecture & Dependency Validation (PART 2B).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from enum import Enum
import hashlib
import json
from typing import Any, Dict, List, Optional, Set, Tuple, Union


class ArchitectureLayer(str, Enum):
    DOMAIN = "DOMAIN"
    APPLICATION = "APPLICATION"
    INTERFACES = "INTERFACES"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    API = "API"
    AGENTS = "AGENTS"
    RUNTIME = "RUNTIME"
    WORKERS = "WORKERS"
    KNOWLEDGE = "KNOWLEDGE"
    SECURITY = "SECURITY"
    OBSERVABILITY = "OBSERVABILITY"
    UNKNOWN = "UNKNOWN"


class ImportType(str, Enum):
    DIRECT_IMPORT = "DIRECT_IMPORT"
    FROM_IMPORT = "FROM_IMPORT"
    RELATIVE_IMPORT = "RELATIVE_IMPORT"
    DYNAMIC_IMPORT = "DYNAMIC_IMPORT"


class CleanArchSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class CleanArchAction(str, Enum):
    BLOCK_BUILD = "BLOCK_BUILD"
    REQUIRE_WAIVER = "REQUIRE_WAIVER"
    WARN = "WARN"


@dataclass
class LayerDependencyRule:
    """Configurable rule governing allowed layer-to-layer dependencies."""
    source_layer: ArchitectureLayer
    allowed_target_layers: List[ArchitectureLayer]
    forbidden_target_layers: List[ArchitectureLayer]
    forbidden_external_packages: List[str] = field(default_factory=list)
    description: str = ""


@dataclass
class CleanArchDependencyEdge:
    """Directed import edge between two modules."""
    source_module: str
    source_layer: ArchitectureLayer
    target_module: str
    target_layer: ArchitectureLayer
    import_type: ImportType
    line_number: int
    is_allowed: bool = True
    violation_reason: Optional[str] = None
    is_waived: bool = False
    waiver_id: Optional[str] = None


@dataclass
class CleanArchViolation:
    """Violation of Clean Architecture dependency direction or forbidden imports."""
    violation_id: str
    rule_id: str
    source_file: str
    source_layer: ArchitectureLayer
    target_module: str
    target_layer: ArchitectureLayer
    line_number: int
    severity: CleanArchSeverity
    message: str
    suggested_fix: str
    action: CleanArchAction = CleanArchAction.BLOCK_BUILD


@dataclass
class ModuleQualityMetrics:
    """Robert C. Martin's Package Coupling & Instability Metrics."""
    module_name: str
    afferent_coupling_ca: int  # Incoming dependencies (who depends on this)
    efferent_coupling_ce: int  # Outgoing dependencies (what this depends on)
    instability_i: float       # I = Ce / (Ca + Ce), 0 = completely stable, 1 = unstable
    abstract_classes_count: int = 0
    total_classes_count: int = 0
    abstractness_a: float = 0.0  # A = Abstract / Total
    distance_from_main_sequence_d: float = 0.0  # D = |A + I - 1|
    architecture_risk: str = "LOW"

    def calculate_metrics(self):
        total_coupling = self.afferent_coupling_ca + self.efferent_coupling_ce
        self.instability_i = round(self.efferent_coupling_ce / total_coupling, 3) if total_coupling > 0 else 0.0
        self.abstractness_a = round(self.abstract_classes_count / self.total_classes_count, 3) if self.total_classes_count > 0 else 0.0
        self.distance_from_main_sequence_d = round(abs(self.abstractness_a + self.instability_i - 1.0), 3)

        if self.distance_from_main_sequence_d > 0.7:
            self.architecture_risk = "HIGH"
        elif self.distance_from_main_sequence_d > 0.4:
            self.architecture_risk = "MEDIUM"
        else:
            self.architecture_risk = "LOW"


@dataclass
class ArchitectureExceptionWaiver:
    """Approved exception waiver bypassing a rule for a specific file/module."""
    waiver_id: str
    rule_id: str
    source_file: str
    target_module: str
    justification: str
    approved_by: str
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    expires_at: str = field(default_factory=lambda: (datetime.now(timezone.utc) + timedelta(days=90)).isoformat())

    def is_active(self) -> bool:
        now_dt = datetime.now(timezone.utc)
        expires_dt = datetime.fromisoformat(self.expires_at)
        return now_dt <= expires_dt


@dataclass
class CleanArchEvidencePackage:
    """Comprehensive evidence generated by dependency validation scan."""
    scan_id: str
    repository_name: str = "DocuTask-Agent"
    commit_sha: str = "HEAD"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    total_modules_analyzed: int = 0
    total_dependencies_extracted: int = 0
    violations: List[CleanArchViolation] = field(default_factory=list)
    circular_dependency_cycles: List[List[str]] = field(default_factory=list)
    module_metrics: Dict[str, ModuleQualityMetrics] = field(default_factory=dict)
    active_waivers: List[ArchitectureExceptionWaiver] = field(default_factory=list)
    clean_architecture_certified: bool = False
    evidence_sha256: str = ""

    def compute_sha256(self) -> str:
        payload = f"{self.scan_id}:{self.timestamp}:{len(self.violations)}:{len(self.circular_dependency_cycles)}:{self.clean_architecture_certified}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()
