import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { scientificApiClient } from '../../services/scientificApiClient';
import { MetricProvenanceModal } from '../../components/telemetry/MetricProvenanceModal';
export const RuntimeStatisticsDashboard = () => {
    const [provenanceMap, setProvenanceMap] = useState({});
    const [selectedProvenance, setSelectedProvenance] = useState(null);
    useEffect(() => {
        scientificApiClient
            .fetchMetricProvenance()
            .then((records) => {
            if (typeof records === 'object' && !Array.isArray(records)) {
                setProvenanceMap(records);
            }
        })
            .catch(() => {
            // Fallback default provenance map
            setProvenanceMap({
                worker_utilization: {
                    metric_id: 'worker_utilization',
                    metric_name: 'Worker Utilization',
                    metric_version: '2.0',
                    value: 0.9214,
                    formatted_value: '92.14%',
                    unit: 'PERCENTAGE',
                    formula_id: 'FORMULA_WORKER_UTILIZATION',
                    formula_expression: 'sum(active_worker_time) / sum(allocated_worker_time)',
                    formula_latex: '\\mathcal{U} = \\frac{\\sum t_{\\text{active}}}{\\sum t_{\\text{allocated}}}',
                    variables_used: { active_time_ms: 4520.0, allocated_time_ms: 4905.0 },
                    raw_event_ids: ['evt_w1', 'evt_w2', 'evt_w3'],
                    sample_size: 483,
                    observation_window: { duration_seconds: 12.41 },
                    statistical_summary: {
                        sample_size: 483,
                        mean: 0.9214,
                        median: 0.9200,
                        mode: 0.9200,
                        variance: 0.0012,
                        standard_deviation: 0.0346,
                        standard_error: 0.0015,
                        min_value: 0.82,
                        max_value: 0.98,
                        p50: 0.92,
                        p90: 0.96,
                        p95: 0.97,
                        p99: 0.98,
                        confidence_interval_95: [0.9184, 0.9244],
                        margin_of_error_95: 0.003,
                        distribution_model: 'STANDARD_NORMAL',
                    },
                    merkle_events_root_sha256: '9a7b...merkleProof483',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['runtime', 'workers', 'efficiency'],
                },
                planner_throughput: {
                    metric_id: 'planner_throughput',
                    metric_name: 'Planner Throughput',
                    metric_version: '2.0',
                    value: 4.82,
                    formatted_value: '4.820 Hz',
                    unit: 'HERTZ',
                    formula_id: 'FORMULA_PLANNER_THROUGHPUT',
                    formula_expression: 'completed_tasks / planner_duration_sec',
                    formula_latex: '\\mathcal{T}_P = \\frac{N_{\\text{completed}}}{\\Delta t_{\\text{planner}}}',
                    variables_used: { completed_tasks: 24, planner_duration_sec: 4.98 },
                    raw_event_ids: ['evt_p1', 'evt_p2'],
                    sample_size: 58,
                    observation_window: { duration_seconds: 4.98 },
                    statistical_summary: null,
                    merkle_events_root_sha256: '8b6c...merkleProof58',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['planner', 'throughput'],
                },
                retry_rate: {
                    metric_id: 'retry_rate',
                    metric_name: 'Execution Retry Rate',
                    metric_version: '2.0',
                    value: 0.034,
                    formatted_value: '3.40%',
                    unit: 'PERCENTAGE',
                    formula_id: 'FORMULA_RETRY_RATE',
                    formula_expression: 'retries_count / execution_attempts',
                    formula_latex: '\\mathcal{R}_{\\text{retry}} = \\frac{N_{\\text{retries}}}{N_{\\text{attempts}}}',
                    variables_used: { retries_count: 2, execution_attempts: 58 },
                    raw_event_ids: ['evt_r1', 'evt_r2'],
                    sample_size: 58,
                    observation_window: { duration_seconds: 12.41 },
                    statistical_summary: null,
                    merkle_events_root_sha256: '7c5d...merkleProof58',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['reliability', 'fault-tolerance'],
                },
                memory_hit_rate: {
                    metric_id: 'memory_hit_rate',
                    metric_name: 'Memory Hit Rate',
                    metric_version: '2.0',
                    value: 0.944,
                    formatted_value: '94.40%',
                    unit: 'PERCENTAGE',
                    formula_id: 'FORMULA_MEMORY_HIT_RATE',
                    formula_expression: 'memory_hits / memory_queries',
                    formula_latex: '\\mathcal{H}_{\\text{mem}} = \\frac{N_{\\text{hits}}}{N_{\\text{queries}}}',
                    variables_used: { memory_hits: 17, memory_queries: 18 },
                    raw_event_ids: ['evt_m1', 'evt_m2'],
                    sample_size: 18,
                    observation_window: { duration_seconds: 12.41 },
                    statistical_summary: null,
                    merkle_events_root_sha256: '6d4e...merkleProof18',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['memory', 'experience'],
                },
                average_latency: {
                    metric_id: 'average_latency',
                    metric_name: 'Average Event Latency',
                    metric_version: '2.0',
                    value: 18.4,
                    formatted_value: '18.4 ms',
                    unit: 'MILLISECONDS',
                    formula_id: 'FORMULA_AVERAGE_LATENCY',
                    formula_expression: 'sum(latency_ms) / event_count',
                    formula_latex: '\\bar{\\mathcal{L}} = \\frac{1}{N} \\sum \\ell_i',
                    variables_used: { total_latency_ms: 8887.2, event_count: 483 },
                    raw_event_ids: ['evt_l1', 'evt_l2'],
                    sample_size: 483,
                    observation_window: { duration_seconds: 12.41 },
                    statistical_summary: {
                        sample_size: 483,
                        mean: 18.4,
                        median: 16.2,
                        mode: 15.0,
                        variance: 14.8,
                        standard_deviation: 3.85,
                        standard_error: 0.175,
                        min_value: 8.2,
                        max_value: 45.0,
                        p50: 16.2,
                        p90: 24.5,
                        p95: 29.8,
                        p99: 38.5,
                        confidence_interval_95: [18.05, 18.75],
                        margin_of_error_95: 0.35,
                        distribution_model: 'STANDARD_NORMAL',
                    },
                    merkle_events_root_sha256: '5e3f...merkleProof483',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['latency', 'performance'],
                },
                parallelism: {
                    metric_id: 'parallelism',
                    metric_name: 'Worker Parallelism Factor',
                    metric_version: '2.0',
                    value: 4.65,
                    formatted_value: '4.65',
                    unit: 'COUNT',
                    formula_id: 'FORMULA_PARALLELISM',
                    formula_expression: 'sum(worker_intervals) / total_span_sec',
                    formula_latex: '\\mathcal{P} = \\frac{1}{T} \\int w(t) \\, dt',
                    variables_used: { worker_intervals_sum: 57.7, total_span_sec: 12.41 },
                    raw_event_ids: ['evt_par1'],
                    sample_size: 58,
                    observation_window: { duration_seconds: 12.41 },
                    statistical_summary: null,
                    merkle_events_root_sha256: '4f2a...merkleProof58',
                    calculated_at_utc: '2026-09-09T12:42:16Z',
                    sentinel_state: null,
                    tags: ['concurrency', 'scaling'],
                },
            });
        });
    }, []);
    return (_jsxs(Card, { className: "w-full bg-[#0F172A]/90 border-[#1E293B] shadow-2xl overflow-hidden", children: [_jsxs(CardHeader, { className: "flex flex-row items-center justify-between py-4 px-6 border-b border-[#1E293B] bg-[#131D35]/50", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "intelligence", size: "sm", children: "EMPIRICAL PROVENANCE" }), _jsx("span", { className: "text-xs text-[#94A3B8] font-mono", children: "100% Derived from Real RuntimeEvents" })] }), _jsx(CardTitle, { className: "mt-1 text-base font-bold text-[#F8FAFC]", children: "Scientifically Grounded Runtime Statistics" })] }), _jsx("div", { className: "text-xs font-mono text-cyan-400 bg-slate-950 px-3 py-1.5 rounded-lg border border-cyan-500/30", children: "Click any metric to inspect formula provenance \u2197" })] }), _jsxs(CardContent, { className: "p-6 space-y-6", children: [_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4", children: Object.values(provenanceMap).map((rec) => (_jsxs("div", { onClick: () => setSelectedProvenance(rec), className: "p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-cyan-500/60 hover:bg-[#131d35] transition-all cursor-pointer group space-y-3 font-mono text-xs", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-semibold text-slate-200 font-sans text-sm", children: rec.metric_name }), _jsx("span", { className: "text-[10px] text-cyan-400 opacity-0 group-hover:opacity-100 transition-opacity font-bold", children: "Inspect \u2197" })] }), _jsxs("div", { className: "flex items-baseline justify-between", children: [_jsx("span", { className: "text-2xl font-extrabold text-cyan-400 font-mono", children: rec.formatted_value }), _jsxs("span", { className: "text-[11px] text-slate-400 font-normal", children: ["n = ", rec.sample_size] })] }), _jsxs("div", { className: "pt-2 border-t border-slate-900 flex items-center justify-between text-[11px] text-slate-400", children: [_jsx("span", { className: "truncate max-w-[180px] text-slate-400 font-mono text-[10px]", children: rec.formula_expression }), _jsxs("span", { className: "text-emerald-400 font-bold text-[10px]", children: ["v", rec.metric_version] })] })] }, rec.metric_id))) }), _jsx(MetricProvenanceModal, { provenance: selectedProvenance, onClose: () => setSelectedProvenance(null) })] })] }));
};
