"""Domain package for incident response automation."""

from app.platform_verification.incident_response_automation.domain.models import (
    ActionRiskLevel,
    CausalChainNode,
    CICDPipelineReport,
    DetectedIncidentSignal,
    IncidentArchitectureReport,
    IncidentAutomationTier,
    IncidentCategory,
    IncidentClassificationItem,
    IncidentClassificationReport,
    IncidentCorrelationReport,
    IncidentDetectionReport,
    IncidentKnowledgeItem,
    IncidentKnowledgeReport,
    IncidentQualityScorecard,
    IncidentSecurityReport,
    IncidentSeverity,
    IncidentStatus,
    PostmortemReport,
    PostmortemTimelineItem,
    RecoveryPolicyReport,
    RecoveryPolicyRule,
    RunbookExecutionReport,
    RunbookStepResult,
    SecurityAuditCheck,
    SelfHealingReport,
    SelfHealingTestResult,
)

# Alias for backwards compatibility
IncidentActionRisk = ActionRiskLevel

__all__ = [
    "IncidentSeverity",
    "IncidentCategory",
    "IncidentStatus",
    "ActionRiskLevel",
    "IncidentActionRisk",
    "IncidentAutomationTier",
    "IncidentArchitectureReport",
    "DetectedIncidentSignal",
    "IncidentDetectionReport",
    "IncidentClassificationItem",
    "IncidentClassificationReport",
    "RunbookStepResult",
    "RunbookExecutionReport",
    "SelfHealingTestResult",
    "SelfHealingReport",
    "RecoveryPolicyRule",
    "RecoveryPolicyReport",
    "CausalChainNode",
    "IncidentCorrelationReport",
    "IncidentKnowledgeItem",
    "IncidentKnowledgeReport",
    "PostmortemTimelineItem",
    "PostmortemReport",
    "SecurityAuditCheck",
    "IncidentSecurityReport",
    "CICDPipelineReport",
    "IncidentQualityScorecard",
]
