apiVersion: v1
kind: Service
metadata:
  name: verification-platform-svc
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: verification-platform
