import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Card } from '../../components/ui/Card';
export const ParetoFrontierView = () => {
    const paretoPoints = [
        { id: 'P1', name: 'Ultra-Fast Wavefront', accuracy: 0.912, latencyMs: 320, costUsd: 0.002, isSelected: false },
        { id: 'P2', name: 'Balanced Hybrid Optimizer', accuracy: 0.985, latencyMs: 650, costUsd: 0.012, isSelected: true },
        { id: 'P3', name: 'High Precision Ensemble', accuracy: 0.992, latencyMs: 1400, costUsd: 0.028, isSelected: false },
        { id: 'P4', name: 'Max Reasoning Gemini Pro', accuracy: 0.998, latencyMs: 2400, costUsd: 0.045, isSelected: false },
    ];
    const dominatedPoints = [
        { id: 'D1', name: 'Greedy Heuristic Single-Pass', accuracy: 0.935, latencyMs: 1450, costUsd: 0.028 },
        { id: 'D2', name: 'Naive Retry Loop', accuracy: 0.920, latencyMs: 2100, costUsd: 0.035 },
        { id: 'D3', name: 'Uncalibrated Model Route', accuracy: 0.890, latencyMs: 980, costUsd: 0.019 },
    ];
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "p-6 rounded-2xl bg-[#0F172A] border border-[#1E293B] shadow-xl", children: _jsxs("div", { className: "flex flex-col md:flex-row items-start md:items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-xl", children: "\uD83D\uDCC8" }), _jsx("h2", { className: "text-lg font-bold font-mono text-[#F8FAFC]", children: "Pareto Frontier & Trade-off Surface" }), _jsx(Badge, { variant: "intelligence", size: "sm", children: "NON-DOMINATED SORTING" })] }), _jsx("p", { className: "text-xs text-[#94A3B8] mt-1", children: "Visualizing the non-dominated Pareto optimal set against strictly dominated candidate execution trajectories." })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-xs font-mono text-[#94A3B8]", children: "Hypervolume (HV)" }), _jsx("div", { className: "text-lg font-mono font-bold text-cyan-400", children: "0.8942" })] }), _jsxs("div", { className: "text-right border-l border-[#1E293B] pl-4", children: [_jsx("div", { className: "text-xs font-mono text-[#94A3B8]", children: "Frontier Density" }), _jsx("div", { className: "text-lg font-mono font-bold text-emerald-400", children: "4 Points" })] })] })] }) }), _jsxs(Card, { className: "p-6 bg-[#0F172A] border border-[#1E293B] space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-sm font-bold font-mono text-[#F8FAFC]", children: "Trade-off Plane: Accuracy (%) vs Latency (ms) vs Cost ($)" }), _jsxs("div", { className: "flex items-center gap-3 text-xs font-mono", children: [_jsxs("span", { className: "flex items-center gap-1 text-emerald-400", children: [_jsx("span", { className: "h-2.5 w-2.5 rounded-full bg-emerald-400 inline-block" }), " Pareto Optimal"] }), _jsxs("span", { className: "flex items-center gap-1 text-[#64748B]", children: [_jsx("span", { className: "h-2.5 w-2.5 rounded-full bg-rose-500/60 inline-block" }), " Dominated Plan"] })] })] }), _jsxs("div", { className: "relative h-64 bg-[#0A0F1D] rounded-xl border border-[#1E293B] p-4 flex flex-col justify-between", children: [_jsx("div", { className: "text-[10px] font-mono text-[#64748B]", children: "\u25B2 Accuracy (Ideal: 100%)" }), _jsxs("div", { className: "relative w-full h-44", children: [_jsx("svg", { className: "absolute inset-0 w-full h-full pointer-events-none", children: _jsx("polyline", { fill: "none", stroke: "#06b6d4", strokeWidth: "2", strokeDasharray: "4,4", points: "80,140 240,40 480,24 720,12" }) }), paretoPoints.map((p) => {
                                        const leftPos = `${(p.latencyMs / 2600) * 85 + 5}%`;
                                        const topPos = `${(1 - (p.accuracy - 0.88) / 0.12) * 75 + 10}%`;
                                        return (_jsxs("div", { style: { left: leftPos, top: topPos }, className: `absolute -translate-x-1/2 -translate-y-1/2 group cursor-pointer`, children: [_jsx("div", { className: `h-4 w-4 rounded-full flex items-center justify-center text-[9px] font-bold font-mono text-black transition-transform group-hover:scale-125 ${p.isSelected ? 'bg-emerald-400 ring-4 ring-emerald-500/30' : 'bg-cyan-400'}`, children: p.id }), _jsxs("div", { className: "hidden group-hover:block absolute bottom-6 left-1/2 -translate-x-1/2 bg-[#0F172A] border border-[#334155] p-2 rounded-lg text-[10px] font-mono whitespace-nowrap shadow-xl z-20", children: [_jsx("div", { className: "font-bold text-[#F8FAFC]", children: p.name }), _jsxs("div", { className: "text-emerald-400", children: ["Acc: ", (p.accuracy * 100).toFixed(1), "%"] }), _jsxs("div", { className: "text-cyan-400", children: ["Lat: ", p.latencyMs, "ms | Cost: $", p.costUsd] })] })] }, p.id));
                                    }), dominatedPoints.map((d) => {
                                        const leftPos = `${(d.latencyMs / 2600) * 85 + 5}%`;
                                        const topPos = `${(1 - (d.accuracy - 0.88) / 0.12) * 75 + 10}%`;
                                        return (_jsxs("div", { style: { left: leftPos, top: topPos }, className: "absolute -translate-x-1/2 -translate-y-1/2 group cursor-pointer", children: [_jsx("div", { className: "h-3 w-3 rounded-full bg-rose-500/70 border border-rose-400 text-[8px] flex items-center justify-center font-bold text-white group-hover:scale-125 transition-transform", children: d.id }), _jsxs("div", { className: "hidden group-hover:block absolute bottom-5 left-1/2 -translate-x-1/2 bg-[#0F172A] border border-rose-500/50 p-2 rounded-lg text-[10px] font-mono whitespace-nowrap shadow-xl z-20", children: [_jsxs("div", { className: "font-bold text-rose-300", children: [d.name, " (Dominated)"] }), _jsxs("div", { children: ["Acc: ", (d.accuracy * 100).toFixed(1), "% | Lat: ", d.latencyMs, "ms"] })] })] }, d.id));
                                    })] }), _jsxs("div", { className: "flex justify-between text-[10px] font-mono text-[#64748B]", children: [_jsx("span", { children: "Fast (0ms)" }), _jsx("span", { children: "Execution Latency (ms) \u25BA" }), _jsx("span", { children: "Slow (2600ms)" })] })] })] })] }));
};
