import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { GitBranch, ArrowRight, Zap, } from 'lucide-react';
export const CausalGraphVisualizer = () => {
    const [selectedVar, setSelectedVar] = useState('DAG_CHUNK_PARTITIONING');
    const [interventionVal, setInterventionVal] = useState(2.0);
    const nodes = [
        { id: 'cnode-1', name: 'DAG_CHUNK_PARTITIONING', domain: 'SCHEDULER', description: 'Splits multi-page documents into parallel sub-tasks', baseline: 1.0 },
        { id: 'cnode-2', name: 'OCR_EXTRACTION_LATENCY', domain: 'METRIC', description: 'Mean page extraction latency in milliseconds', baseline: 180.0 },
        { id: 'cnode-3', name: 'TOKEN_EMBEDDING_CACHE_HIT_RATE', domain: 'MEMORY', description: 'Percentage of cached table schema embeddings', baseline: 0.82 },
        { id: 'cnode-4', name: 'TOTAL_COMPUTE_COST_USD', domain: 'FINANCIAL', description: 'End-to-end dollar compute cost per document', baseline: 0.024 },
    ];
    const edges = [
        { source: 'DAG_CHUNK_PARTITIONING', target: 'OCR_EXTRACTION_LATENCY', type: 'DIRECT_CAUSE', strength: -0.425, confidence: 0.992 },
        { source: 'TOKEN_EMBEDDING_CACHE_HIT_RATE', target: 'TOTAL_COMPUTE_COST_USD', type: 'DIRECT_CAUSE', strength: -0.220, confidence: 0.985 },
        { source: 'OCR_EXTRACTION_LATENCY', target: 'TOTAL_COMPUTE_COST_USD', type: 'INDIRECT_CAUSE', strength: 0.150, confidence: 0.960 },
    ];
    const activeNode = nodes.find((n) => n.name === selectedVar) ?? nodes[0];
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-border/40 pb-4", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Causal Reasoning Graph Visualizer" }), _jsx(Badge, { variant: "intelligence", size: "sm", hasDot: true, isPulsing: true, children: "STRUCTURAL CAUSAL MODEL ONLINE" }), _jsx(Badge, { variant: "outline", size: "sm", children: "AWM-PSDTIP Phase 13.10" })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-1", children: "Structural Causal Models (SCM), intervention analysis via do-calculus, root cause propagation, and elimination of spurious correlations." })] }) }), _jsxs(Card, { className: "p-5 bg-gradient-to-r from-blue-950/30 via-purple-950/20 to-background border-blue-500/30 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Zap, { className: "w-5 h-5 text-blue-400" }), _jsx("h2", { className: "text-sm font-bold text-foreground", children: "Do-Calculus Intervention Simulator" })] }), _jsx(Badge, { variant: "success", size: "sm", children: "Intervention Active" })] }), _jsxs("div", { className: "flex flex-col sm:flex-row items-center gap-4 text-xs", children: [_jsxs("div", { className: "w-full sm:w-1/3 space-y-1", children: [_jsx("span", { className: "text-muted-foreground", children: "Intervention Variable:" }), _jsx("select", { value: selectedVar, onChange: (e) => setSelectedVar(e.target.value), className: "w-full bg-secondary/50 text-xs rounded-lg px-3 py-2 border border-border/40 text-foreground", children: nodes.map((n) => (_jsx("option", { value: n.name, children: n.name }, n.id))) })] }), _jsxs("div", { className: "w-full sm:w-1/3 space-y-1", children: [_jsx("span", { className: "text-muted-foreground", children: "Intervention Value (do-operator):" }), _jsx("input", { type: "number", value: interventionVal, onChange: (e) => setInterventionVal(parseFloat(e.target.value) || 0), step: "0.1", className: "w-full bg-secondary/50 text-xs rounded-lg px-3 py-2 border border-border/40 text-foreground" })] }), _jsx("div", { className: "w-full sm:w-1/3 pt-4 sm:pt-0", children: _jsxs("div", { className: "p-3 rounded bg-blue-950/20 border border-blue-500/30 text-xs font-mono", children: [_jsx("span", { className: "text-blue-300", children: "Predicted Downstream Shift:" }), _jsx("div", { className: "text-sm font-bold text-foreground mt-0.5", children: activeNode.name === 'DAG_CHUNK_PARTITIONING'
                                                ? `OCR Latency: -${((interventionVal - activeNode.baseline) * 42.5).toFixed(1)}%`
                                                : 'Stable Causal Lever' })] }) })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-6", children: [_jsxs("div", { className: "lg:col-span-5 space-y-3", children: [_jsxs("h2", { className: "text-xs font-semibold text-muted-foreground uppercase tracking-wider", children: ["Causal Variables (", nodes.length, ")"] }), nodes.map((n) => (_jsxs(Card, { onClick: () => setSelectedVar(n.name), className: `p-4 cursor-pointer transition-all border ${selectedVar === n.name
                                    ? 'border-purple-500/60 bg-purple-950/30 shadow-sm'
                                    : 'border-border/40 bg-secondary/10 hover:bg-secondary/20'}`, children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsx("span", { className: "text-xs font-mono font-bold text-foreground", children: n.name }), _jsx(Badge, { variant: "outline", size: "sm", children: n.domain })] }), _jsx("p", { className: "text-xs text-muted-foreground mt-2", children: n.description }), _jsxs("div", { className: "text-[11px] font-mono text-purple-300 mt-2", children: ["Baseline: ", n.baseline] })] }, n.id)))] }), _jsx("div", { className: "lg:col-span-7 space-y-4", children: _jsxs(Card, { className: "p-5 border-border/40 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(GitBranch, { className: "w-4 h-4 text-purple-400" }), _jsx("h2", { className: "text-base font-semibold", children: "Structural Causal Links" })] }), _jsx(Badge, { variant: "outline", size: "sm", children: "Empirically Proven" })] }), _jsx("div", { className: "space-y-3", children: edges.map((e, idx) => (_jsxs("div", { className: "p-3.5 rounded-lg border border-purple-500/20 bg-purple-950/10 text-xs font-mono space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 text-foreground font-bold", children: [_jsx("span", { children: e.source }), _jsx(ArrowRight, { className: "w-3.5 h-3.5 text-purple-400" }), _jsx("span", { children: e.target })] }), _jsx(Badge, { variant: "success", size: "sm", children: e.type })] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] text-muted-foreground pt-1 border-t border-border/30", children: [_jsxs("span", { children: ["Causal Lever Strength: ", _jsx("strong", { className: "text-foreground", children: e.strength })] }), _jsxs("span", { children: ["Confidence: ", _jsxs("strong", { className: "text-emerald-400", children: [(e.confidence * 100).toFixed(1), "%"] })] })] })] }, idx))) })] }) })] })] }));
};
