import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from '../../utils/cn';
export const LoadingState = ({ variant = 'neural-pulse', message = 'Agent is deliberating...', submessage, thinkingPhase, rowsCount = 3, className, ...props }) => {
    if (variant === 'skeleton') {
        return (_jsxs("div", { className: cn('space-y-3 w-full animate-pulse', className), ...props, children: [_jsx("div", { className: "h-4 bg-[#1E293B] rounded-md w-3/4" }), Array.from({ length: rowsCount }).map((_, i) => (_jsx("div", { className: "h-3 bg-[#131D35] rounded-md", style: { width: `${85 - i * 15}%` } }, i)))] }));
    }
    if (variant === 'cognitive-deliberation') {
        return (_jsxs("div", { className: cn('flex flex-col items-center justify-center p-8 text-center rounded-xl bg-[#131D35]/50 border border-cyan-500/20 shadow-[0_0_30px_rgba(0,210,255,0.08)]', className), ...props, children: [_jsxs("div", { className: "relative flex items-center justify-center h-16 w-16 mb-4", children: [_jsx("div", { className: "absolute inset-0 rounded-full border border-cyan-400/40 animate-ping opacity-25" }), _jsx("div", { className: "absolute inset-2 rounded-full border-2 border-t-[#00D2FF] border-r-transparent border-b-[#0066FF] border-l-transparent animate-spin duration-700" }), _jsx("div", { className: "h-4 w-4 rounded-full bg-gradient-to-tr from-[#0066FF] to-[#00D2FF] shadow-[0_0_12px_rgba(0,210,255,0.8)]" })] }), thinkingPhase && (_jsxs("span", { className: "text-[11px] font-mono uppercase tracking-widest text-[#00D2FF] bg-cyan-950/60 px-2.5 py-0.5 rounded border border-cyan-500/30 mb-2", children: ["Phase: ", thinkingPhase] })), _jsx("h4", { className: "text-sm font-semibold text-[#F8FAFC] tracking-tight", children: message }), submessage && (_jsx("p", { className: "mt-1 max-w-sm text-xs text-[#94A3B8] font-mono leading-relaxed", children: submessage }))] }));
    }
    // Default Neural Pulse Loader
    return (_jsxs("div", { className: cn('flex items-center gap-3 p-4 rounded-lg bg-[#131D35] border border-[#1E293B]', className), role: "status", ...props, children: [_jsxs("div", { className: "relative flex items-center justify-center shrink-0 h-8 w-8", children: [_jsx("span", { className: "animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-20" }), _jsx("span", { className: "relative inline-flex rounded-full h-3 w-3 bg-[#00D2FF] shadow-[0_0_10px_rgba(0,210,255,0.7)]" })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-xs font-medium text-[#F8FAFC]", children: message }), submessage && _jsx("span", { className: "text-[11px] text-[#94A3B8]", children: submessage })] })] }));
};
